// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_streaming/crypto_params.proto

package dev.lavalink.youtube.protos;

public final class CryptoParamsOuterClass {
  private CryptoParamsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CryptoParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:video_streaming.CryptoParams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes hmac = 4;</code>
     * @return Whether the hmac field is set.
     */
    boolean hasHmac();
    /**
     * <code>optional bytes hmac = 4;</code>
     * @return The hmac.
     */
    com.google.protobuf.ByteString getHmac();

    /**
     * <code>optional bytes iv = 5;</code>
     * @return Whether the iv field is set.
     */
    boolean hasIv();
    /**
     * <code>optional bytes iv = 5;</code>
     * @return The iv.
     */
    com.google.protobuf.ByteString getIv();

    /**
     * <code>optional .video_streaming.CryptoParams.CompressionType compression_type = 6;</code>
     * @return Whether the compressionType field is set.
     */
    boolean hasCompressionType();
    /**
     * <code>optional .video_streaming.CryptoParams.CompressionType compression_type = 6;</code>
     * @return The compressionType.
     */
    dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.CompressionType getCompressionType();
  }
  /**
   * Protobuf type {@code video_streaming.CryptoParams}
   */
  public static final class CryptoParams extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:video_streaming.CryptoParams)
      CryptoParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CryptoParams.newBuilder() to construct.
    private CryptoParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CryptoParams() {
      hmac_ = com.google.protobuf.ByteString.EMPTY;
      iv_ = com.google.protobuf.ByteString.EMPTY;
      compressionType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CryptoParams();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.lavalink.youtube.protos.CryptoParamsOuterClass.internal_static_video_streaming_CryptoParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.lavalink.youtube.protos.CryptoParamsOuterClass.internal_static_video_streaming_CryptoParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.class, dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.Builder.class);
    }

    /**
     * Protobuf enum {@code video_streaming.CryptoParams.CompressionType}
     */
    public enum CompressionType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NONE = 0;</code>
       */
      NONE(0),
      /**
       * <code>GZIP = 1;</code>
       */
      GZIP(1),
      /**
       * <code>BROTLI = 2;</code>
       */
      BROTLI(2),
      ;

      /**
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <code>GZIP = 1;</code>
       */
      public static final int GZIP_VALUE = 1;
      /**
       * <code>BROTLI = 2;</code>
       */
      public static final int BROTLI_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CompressionType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static CompressionType forNumber(int value) {
        switch (value) {
          case 0: return NONE;
          case 1: return GZIP;
          case 2: return BROTLI;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CompressionType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CompressionType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompressionType>() {
              public CompressionType findValueByNumber(int number) {
                return CompressionType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.getDescriptor().getEnumTypes().get(0);
      }

      private static final CompressionType[] VALUES = values();

      public static CompressionType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CompressionType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:video_streaming.CryptoParams.CompressionType)
    }

    private int bitField0_;
    public static final int HMAC_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString hmac_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes hmac = 4;</code>
     * @return Whether the hmac field is set.
     */
    @java.lang.Override
    public boolean hasHmac() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes hmac = 4;</code>
     * @return The hmac.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHmac() {
      return hmac_;
    }

    public static final int IV_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes iv = 5;</code>
     * @return Whether the iv field is set.
     */
    @java.lang.Override
    public boolean hasIv() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes iv = 5;</code>
     * @return The iv.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIv() {
      return iv_;
    }

    public static final int COMPRESSION_TYPE_FIELD_NUMBER = 6;
    private int compressionType_ = 0;
    /**
     * <code>optional .video_streaming.CryptoParams.CompressionType compression_type = 6;</code>
     * @return Whether the compressionType field is set.
     */
    @java.lang.Override public boolean hasCompressionType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .video_streaming.CryptoParams.CompressionType compression_type = 6;</code>
     * @return The compressionType.
     */
    @java.lang.Override public dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.CompressionType getCompressionType() {
      dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.CompressionType result = dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.CompressionType.forNumber(compressionType_);
      return result == null ? dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.CompressionType.NONE : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(4, hmac_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(5, iv_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(6, compressionType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, hmac_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, iv_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, compressionType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams)) {
        return super.equals(obj);
      }
      dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams other = (dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams) obj;

      if (hasHmac() != other.hasHmac()) return false;
      if (hasHmac()) {
        if (!getHmac()
            .equals(other.getHmac())) return false;
      }
      if (hasIv() != other.hasIv()) return false;
      if (hasIv()) {
        if (!getIv()
            .equals(other.getIv())) return false;
      }
      if (hasCompressionType() != other.hasCompressionType()) return false;
      if (hasCompressionType()) {
        if (compressionType_ != other.compressionType_) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHmac()) {
        hash = (37 * hash) + HMAC_FIELD_NUMBER;
        hash = (53 * hash) + getHmac().hashCode();
      }
      if (hasIv()) {
        hash = (37 * hash) + IV_FIELD_NUMBER;
        hash = (53 * hash) + getIv().hashCode();
      }
      if (hasCompressionType()) {
        hash = (37 * hash) + COMPRESSION_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + compressionType_;
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code video_streaming.CryptoParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:video_streaming.CryptoParams)
        dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.lavalink.youtube.protos.CryptoParamsOuterClass.internal_static_video_streaming_CryptoParams_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.lavalink.youtube.protos.CryptoParamsOuterClass.internal_static_video_streaming_CryptoParams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.class, dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.Builder.class);
      }

      // Construct using dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        hmac_ = com.google.protobuf.ByteString.EMPTY;
        iv_ = com.google.protobuf.ByteString.EMPTY;
        compressionType_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.lavalink.youtube.protos.CryptoParamsOuterClass.internal_static_video_streaming_CryptoParams_descriptor;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams getDefaultInstanceForType() {
        return dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.getDefaultInstance();
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams build() {
        dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams buildPartial() {
        dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams result = new dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.hmac_ = hmac_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.iv_ = iv_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.compressionType_ = compressionType_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams) {
          return mergeFrom((dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams other) {
        if (other == dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.getDefaultInstance()) return this;
        if (other.hasHmac()) {
          setHmac(other.getHmac());
        }
        if (other.hasIv()) {
          setIv(other.getIv());
        }
        if (other.hasCompressionType()) {
          setCompressionType(other.getCompressionType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 34: {
                hmac_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 34
              case 42: {
                iv_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 42
              case 48: {
                int tmpRaw = input.readEnum();
                dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.CompressionType tmpValue =
                    dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.CompressionType.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(6, tmpRaw);
                } else {
                  compressionType_ = tmpRaw;
                  bitField0_ |= 0x00000004;
                }
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString hmac_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes hmac = 4;</code>
       * @return Whether the hmac field is set.
       */
      @java.lang.Override
      public boolean hasHmac() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes hmac = 4;</code>
       * @return The hmac.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getHmac() {
        return hmac_;
      }
      /**
       * <code>optional bytes hmac = 4;</code>
       * @param value The hmac to set.
       * @return This builder for chaining.
       */
      public Builder setHmac(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        hmac_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes hmac = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHmac() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hmac_ = getDefaultInstance().getHmac();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes iv = 5;</code>
       * @return Whether the iv field is set.
       */
      @java.lang.Override
      public boolean hasIv() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes iv = 5;</code>
       * @return The iv.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getIv() {
        return iv_;
      }
      /**
       * <code>optional bytes iv = 5;</code>
       * @param value The iv to set.
       * @return This builder for chaining.
       */
      public Builder setIv(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        iv_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes iv = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIv() {
        bitField0_ = (bitField0_ & ~0x00000002);
        iv_ = getDefaultInstance().getIv();
        onChanged();
        return this;
      }

      private int compressionType_ = 0;
      /**
       * <code>optional .video_streaming.CryptoParams.CompressionType compression_type = 6;</code>
       * @return Whether the compressionType field is set.
       */
      @java.lang.Override public boolean hasCompressionType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .video_streaming.CryptoParams.CompressionType compression_type = 6;</code>
       * @return The compressionType.
       */
      @java.lang.Override
      public dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.CompressionType getCompressionType() {
        dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.CompressionType result = dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.CompressionType.forNumber(compressionType_);
        return result == null ? dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.CompressionType.NONE : result;
      }
      /**
       * <code>optional .video_streaming.CryptoParams.CompressionType compression_type = 6;</code>
       * @param value The compressionType to set.
       * @return This builder for chaining.
       */
      public Builder setCompressionType(dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams.CompressionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        compressionType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.CryptoParams.CompressionType compression_type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompressionType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        compressionType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:video_streaming.CryptoParams)
    }

    // @@protoc_insertion_point(class_scope:video_streaming.CryptoParams)
    private static final dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams();
    }

    public static dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CryptoParams>
        PARSER = new com.google.protobuf.AbstractParser<CryptoParams>() {
      @java.lang.Override
      public CryptoParams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CryptoParams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CryptoParams> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.lavalink.youtube.protos.CryptoParamsOuterClass.CryptoParams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_video_streaming_CryptoParams_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_video_streaming_CryptoParams_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#video_streaming/crypto_params.proto\022\017v" +
      "ideo_streaming\"\244\001\n\014CryptoParams\022\014\n\004hmac\030" +
      "\004 \001(\014\022\n\n\002iv\030\005 \001(\014\022G\n\020compression_type\030\006 " +
      "\001(\0162-.video_streaming.CryptoParams.Compr" +
      "essionType\"1\n\017CompressionType\022\010\n\004NONE\020\000\022" +
      "\010\n\004GZIP\020\001\022\n\n\006BROTLI\020\002B\035\n\033dev.lavalink.yo" +
      "utube.protos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_video_streaming_CryptoParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_video_streaming_CryptoParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_video_streaming_CryptoParams_descriptor,
        new java.lang.String[] { "Hmac", "Iv", "CompressionType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
