// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_streaming/media_header.proto

package dev.lavalink.youtube.protos;

public final class MediaHeaderOuterClass {
  private MediaHeaderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MediaHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:video_streaming.MediaHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 header_id = 1;</code>
     * @return Whether the headerId field is set.
     */
    boolean hasHeaderId();
    /**
     * <code>optional uint32 header_id = 1;</code>
     * @return The headerId.
     */
    int getHeaderId();

    /**
     * <code>optional string video_id = 2;</code>
     * @return Whether the videoId field is set.
     */
    boolean hasVideoId();
    /**
     * <code>optional string video_id = 2;</code>
     * @return The videoId.
     */
    java.lang.String getVideoId();
    /**
     * <code>optional string video_id = 2;</code>
     * @return The bytes for videoId.
     */
    com.google.protobuf.ByteString
        getVideoIdBytes();

    /**
     * <code>optional int32 itag = 3;</code>
     * @return Whether the itag field is set.
     */
    boolean hasItag();
    /**
     * <code>optional int32 itag = 3;</code>
     * @return The itag.
     */
    int getItag();

    /**
     * <code>optional uint64 lmt = 4;</code>
     * @return Whether the lmt field is set.
     */
    boolean hasLmt();
    /**
     * <code>optional uint64 lmt = 4;</code>
     * @return The lmt.
     */
    long getLmt();

    /**
     * <code>optional string xtags = 5;</code>
     * @return Whether the xtags field is set.
     */
    boolean hasXtags();
    /**
     * <code>optional string xtags = 5;</code>
     * @return The xtags.
     */
    java.lang.String getXtags();
    /**
     * <code>optional string xtags = 5;</code>
     * @return The bytes for xtags.
     */
    com.google.protobuf.ByteString
        getXtagsBytes();

    /**
     * <code>optional int64 start_range = 6;</code>
     * @return Whether the startRange field is set.
     */
    boolean hasStartRange();
    /**
     * <code>optional int64 start_range = 6;</code>
     * @return The startRange.
     */
    long getStartRange();

    /**
     * <code>optional .video_streaming.MediaHeader.CompressionAlgorithm compression_algorithm = 7;</code>
     * @return Whether the compressionAlgorithm field is set.
     */
    boolean hasCompressionAlgorithm();
    /**
     * <code>optional .video_streaming.MediaHeader.CompressionAlgorithm compression_algorithm = 7;</code>
     * @return The compressionAlgorithm.
     */
    dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.CompressionAlgorithm getCompressionAlgorithm();

    /**
     * <code>optional bool is_init_seg = 8;</code>
     * @return Whether the isInitSeg field is set.
     */
    boolean hasIsInitSeg();
    /**
     * <code>optional bool is_init_seg = 8;</code>
     * @return The isInitSeg.
     */
    boolean getIsInitSeg();

    /**
     * <code>optional int64 sequence_number = 9;</code>
     * @return Whether the sequenceNumber field is set.
     */
    boolean hasSequenceNumber();
    /**
     * <code>optional int64 sequence_number = 9;</code>
     * @return The sequenceNumber.
     */
    long getSequenceNumber();

    /**
     * <code>optional int64 field10 = 10;</code>
     * @return Whether the field10 field is set.
     */
    boolean hasField10();
    /**
     * <code>optional int64 field10 = 10;</code>
     * @return The field10.
     */
    long getField10();

    /**
     * <code>optional int64 start_ms = 11;</code>
     * @return Whether the startMs field is set.
     */
    boolean hasStartMs();
    /**
     * <code>optional int64 start_ms = 11;</code>
     * @return The startMs.
     */
    long getStartMs();

    /**
     * <code>optional int64 duration_ms = 12;</code>
     * @return Whether the durationMs field is set.
     */
    boolean hasDurationMs();
    /**
     * <code>optional int64 duration_ms = 12;</code>
     * @return The durationMs.
     */
    long getDurationMs();

    /**
     * <code>optional .misc.FormatId format_id = 13;</code>
     * @return Whether the formatId field is set.
     */
    boolean hasFormatId();
    /**
     * <code>optional .misc.FormatId format_id = 13;</code>
     * @return The formatId.
     */
    dev.lavalink.youtube.protos.Common.FormatId getFormatId();
    /**
     * <code>optional .misc.FormatId format_id = 13;</code>
     */
    dev.lavalink.youtube.protos.Common.FormatIdOrBuilder getFormatIdOrBuilder();

    /**
     * <code>optional int64 content_length = 14;</code>
     * @return Whether the contentLength field is set.
     */
    boolean hasContentLength();
    /**
     * <code>optional int64 content_length = 14;</code>
     * @return The contentLength.
     */
    long getContentLength();

    /**
     * <code>optional .video_streaming.TimeRange time_range = 15;</code>
     * @return Whether the timeRange field is set.
     */
    boolean hasTimeRange();
    /**
     * <code>optional .video_streaming.TimeRange time_range = 15;</code>
     * @return The timeRange.
     */
    dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange getTimeRange();
    /**
     * <code>optional .video_streaming.TimeRange time_range = 15;</code>
     */
    dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRangeOrBuilder getTimeRangeOrBuilder();
  }
  /**
   * Protobuf type {@code video_streaming.MediaHeader}
   */
  public static final class MediaHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:video_streaming.MediaHeader)
      MediaHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MediaHeader.newBuilder() to construct.
    private MediaHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MediaHeader() {
      videoId_ = "";
      xtags_ = "";
      compressionAlgorithm_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MediaHeader();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.lavalink.youtube.protos.MediaHeaderOuterClass.internal_static_video_streaming_MediaHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.lavalink.youtube.protos.MediaHeaderOuterClass.internal_static_video_streaming_MediaHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.class, dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.Builder.class);
    }

    /**
     * Protobuf enum {@code video_streaming.MediaHeader.CompressionAlgorithm}
     */
    public enum CompressionAlgorithm
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>NONE = 1;</code>
       */
      NONE(1),
      /**
       * <code>GZIP = 2;</code>
       */
      GZIP(2),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>NONE = 1;</code>
       */
      public static final int NONE_VALUE = 1;
      /**
       * <code>GZIP = 2;</code>
       */
      public static final int GZIP_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CompressionAlgorithm valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static CompressionAlgorithm forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return NONE;
          case 2: return GZIP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CompressionAlgorithm>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CompressionAlgorithm> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompressionAlgorithm>() {
              public CompressionAlgorithm findValueByNumber(int number) {
                return CompressionAlgorithm.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.getDescriptor().getEnumTypes().get(0);
      }

      private static final CompressionAlgorithm[] VALUES = values();

      public static CompressionAlgorithm valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CompressionAlgorithm(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:video_streaming.MediaHeader.CompressionAlgorithm)
    }

    private int bitField0_;
    public static final int HEADER_ID_FIELD_NUMBER = 1;
    private int headerId_ = 0;
    /**
     * <code>optional uint32 header_id = 1;</code>
     * @return Whether the headerId field is set.
     */
    @java.lang.Override
    public boolean hasHeaderId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 header_id = 1;</code>
     * @return The headerId.
     */
    @java.lang.Override
    public int getHeaderId() {
      return headerId_;
    }

    public static final int VIDEO_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object videoId_ = "";
    /**
     * <code>optional string video_id = 2;</code>
     * @return Whether the videoId field is set.
     */
    @java.lang.Override
    public boolean hasVideoId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string video_id = 2;</code>
     * @return The videoId.
     */
    @java.lang.Override
    public java.lang.String getVideoId() {
      java.lang.Object ref = videoId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          videoId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string video_id = 2;</code>
     * @return The bytes for videoId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVideoIdBytes() {
      java.lang.Object ref = videoId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        videoId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ITAG_FIELD_NUMBER = 3;
    private int itag_ = 0;
    /**
     * <code>optional int32 itag = 3;</code>
     * @return Whether the itag field is set.
     */
    @java.lang.Override
    public boolean hasItag() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 itag = 3;</code>
     * @return The itag.
     */
    @java.lang.Override
    public int getItag() {
      return itag_;
    }

    public static final int LMT_FIELD_NUMBER = 4;
    private long lmt_ = 0L;
    /**
     * <code>optional uint64 lmt = 4;</code>
     * @return Whether the lmt field is set.
     */
    @java.lang.Override
    public boolean hasLmt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint64 lmt = 4;</code>
     * @return The lmt.
     */
    @java.lang.Override
    public long getLmt() {
      return lmt_;
    }

    public static final int XTAGS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object xtags_ = "";
    /**
     * <code>optional string xtags = 5;</code>
     * @return Whether the xtags field is set.
     */
    @java.lang.Override
    public boolean hasXtags() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string xtags = 5;</code>
     * @return The xtags.
     */
    @java.lang.Override
    public java.lang.String getXtags() {
      java.lang.Object ref = xtags_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          xtags_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string xtags = 5;</code>
     * @return The bytes for xtags.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getXtagsBytes() {
      java.lang.Object ref = xtags_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        xtags_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_RANGE_FIELD_NUMBER = 6;
    private long startRange_ = 0L;
    /**
     * <code>optional int64 start_range = 6;</code>
     * @return Whether the startRange field is set.
     */
    @java.lang.Override
    public boolean hasStartRange() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int64 start_range = 6;</code>
     * @return The startRange.
     */
    @java.lang.Override
    public long getStartRange() {
      return startRange_;
    }

    public static final int COMPRESSION_ALGORITHM_FIELD_NUMBER = 7;
    private int compressionAlgorithm_ = 0;
    /**
     * <code>optional .video_streaming.MediaHeader.CompressionAlgorithm compression_algorithm = 7;</code>
     * @return Whether the compressionAlgorithm field is set.
     */
    @java.lang.Override public boolean hasCompressionAlgorithm() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .video_streaming.MediaHeader.CompressionAlgorithm compression_algorithm = 7;</code>
     * @return The compressionAlgorithm.
     */
    @java.lang.Override public dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.CompressionAlgorithm getCompressionAlgorithm() {
      dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.CompressionAlgorithm result = dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.CompressionAlgorithm.forNumber(compressionAlgorithm_);
      return result == null ? dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.CompressionAlgorithm.UNKNOWN : result;
    }

    public static final int IS_INIT_SEG_FIELD_NUMBER = 8;
    private boolean isInitSeg_ = false;
    /**
     * <code>optional bool is_init_seg = 8;</code>
     * @return Whether the isInitSeg field is set.
     */
    @java.lang.Override
    public boolean hasIsInitSeg() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional bool is_init_seg = 8;</code>
     * @return The isInitSeg.
     */
    @java.lang.Override
    public boolean getIsInitSeg() {
      return isInitSeg_;
    }

    public static final int SEQUENCE_NUMBER_FIELD_NUMBER = 9;
    private long sequenceNumber_ = 0L;
    /**
     * <code>optional int64 sequence_number = 9;</code>
     * @return Whether the sequenceNumber field is set.
     */
    @java.lang.Override
    public boolean hasSequenceNumber() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional int64 sequence_number = 9;</code>
     * @return The sequenceNumber.
     */
    @java.lang.Override
    public long getSequenceNumber() {
      return sequenceNumber_;
    }

    public static final int FIELD10_FIELD_NUMBER = 10;
    private long field10_ = 0L;
    /**
     * <code>optional int64 field10 = 10;</code>
     * @return Whether the field10 field is set.
     */
    @java.lang.Override
    public boolean hasField10() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional int64 field10 = 10;</code>
     * @return The field10.
     */
    @java.lang.Override
    public long getField10() {
      return field10_;
    }

    public static final int START_MS_FIELD_NUMBER = 11;
    private long startMs_ = 0L;
    /**
     * <code>optional int64 start_ms = 11;</code>
     * @return Whether the startMs field is set.
     */
    @java.lang.Override
    public boolean hasStartMs() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional int64 start_ms = 11;</code>
     * @return The startMs.
     */
    @java.lang.Override
    public long getStartMs() {
      return startMs_;
    }

    public static final int DURATION_MS_FIELD_NUMBER = 12;
    private long durationMs_ = 0L;
    /**
     * <code>optional int64 duration_ms = 12;</code>
     * @return Whether the durationMs field is set.
     */
    @java.lang.Override
    public boolean hasDurationMs() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional int64 duration_ms = 12;</code>
     * @return The durationMs.
     */
    @java.lang.Override
    public long getDurationMs() {
      return durationMs_;
    }

    public static final int FORMAT_ID_FIELD_NUMBER = 13;
    private dev.lavalink.youtube.protos.Common.FormatId formatId_;
    /**
     * <code>optional .misc.FormatId format_id = 13;</code>
     * @return Whether the formatId field is set.
     */
    @java.lang.Override
    public boolean hasFormatId() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <code>optional .misc.FormatId format_id = 13;</code>
     * @return The formatId.
     */
    @java.lang.Override
    public dev.lavalink.youtube.protos.Common.FormatId getFormatId() {
      return formatId_ == null ? dev.lavalink.youtube.protos.Common.FormatId.getDefaultInstance() : formatId_;
    }
    /**
     * <code>optional .misc.FormatId format_id = 13;</code>
     */
    @java.lang.Override
    public dev.lavalink.youtube.protos.Common.FormatIdOrBuilder getFormatIdOrBuilder() {
      return formatId_ == null ? dev.lavalink.youtube.protos.Common.FormatId.getDefaultInstance() : formatId_;
    }

    public static final int CONTENT_LENGTH_FIELD_NUMBER = 14;
    private long contentLength_ = 0L;
    /**
     * <code>optional int64 content_length = 14;</code>
     * @return Whether the contentLength field is set.
     */
    @java.lang.Override
    public boolean hasContentLength() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <code>optional int64 content_length = 14;</code>
     * @return The contentLength.
     */
    @java.lang.Override
    public long getContentLength() {
      return contentLength_;
    }

    public static final int TIME_RANGE_FIELD_NUMBER = 15;
    private dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange timeRange_;
    /**
     * <code>optional .video_streaming.TimeRange time_range = 15;</code>
     * @return Whether the timeRange field is set.
     */
    @java.lang.Override
    public boolean hasTimeRange() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <code>optional .video_streaming.TimeRange time_range = 15;</code>
     * @return The timeRange.
     */
    @java.lang.Override
    public dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange getTimeRange() {
      return timeRange_ == null ? dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange.getDefaultInstance() : timeRange_;
    }
    /**
     * <code>optional .video_streaming.TimeRange time_range = 15;</code>
     */
    @java.lang.Override
    public dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRangeOrBuilder getTimeRangeOrBuilder() {
      return timeRange_ == null ? dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange.getDefaultInstance() : timeRange_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, headerId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, videoId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, itag_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt64(4, lmt_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, xtags_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt64(6, startRange_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeEnum(7, compressionAlgorithm_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeBool(8, isInitSeg_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeInt64(9, sequenceNumber_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeInt64(10, field10_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        output.writeInt64(11, startMs_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        output.writeInt64(12, durationMs_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        output.writeMessage(13, getFormatId());
      }
      if (((bitField0_ & 0x00002000) != 0)) {
        output.writeInt64(14, contentLength_);
      }
      if (((bitField0_ & 0x00004000) != 0)) {
        output.writeMessage(15, getTimeRange());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, headerId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, videoId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, itag_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, lmt_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, xtags_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, startRange_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, compressionAlgorithm_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, isInitSeg_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, sequenceNumber_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, field10_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, startMs_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, durationMs_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getFormatId());
      }
      if (((bitField0_ & 0x00002000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(14, contentLength_);
      }
      if (((bitField0_ & 0x00004000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, getTimeRange());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader)) {
        return super.equals(obj);
      }
      dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader other = (dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader) obj;

      if (hasHeaderId() != other.hasHeaderId()) return false;
      if (hasHeaderId()) {
        if (getHeaderId()
            != other.getHeaderId()) return false;
      }
      if (hasVideoId() != other.hasVideoId()) return false;
      if (hasVideoId()) {
        if (!getVideoId()
            .equals(other.getVideoId())) return false;
      }
      if (hasItag() != other.hasItag()) return false;
      if (hasItag()) {
        if (getItag()
            != other.getItag()) return false;
      }
      if (hasLmt() != other.hasLmt()) return false;
      if (hasLmt()) {
        if (getLmt()
            != other.getLmt()) return false;
      }
      if (hasXtags() != other.hasXtags()) return false;
      if (hasXtags()) {
        if (!getXtags()
            .equals(other.getXtags())) return false;
      }
      if (hasStartRange() != other.hasStartRange()) return false;
      if (hasStartRange()) {
        if (getStartRange()
            != other.getStartRange()) return false;
      }
      if (hasCompressionAlgorithm() != other.hasCompressionAlgorithm()) return false;
      if (hasCompressionAlgorithm()) {
        if (compressionAlgorithm_ != other.compressionAlgorithm_) return false;
      }
      if (hasIsInitSeg() != other.hasIsInitSeg()) return false;
      if (hasIsInitSeg()) {
        if (getIsInitSeg()
            != other.getIsInitSeg()) return false;
      }
      if (hasSequenceNumber() != other.hasSequenceNumber()) return false;
      if (hasSequenceNumber()) {
        if (getSequenceNumber()
            != other.getSequenceNumber()) return false;
      }
      if (hasField10() != other.hasField10()) return false;
      if (hasField10()) {
        if (getField10()
            != other.getField10()) return false;
      }
      if (hasStartMs() != other.hasStartMs()) return false;
      if (hasStartMs()) {
        if (getStartMs()
            != other.getStartMs()) return false;
      }
      if (hasDurationMs() != other.hasDurationMs()) return false;
      if (hasDurationMs()) {
        if (getDurationMs()
            != other.getDurationMs()) return false;
      }
      if (hasFormatId() != other.hasFormatId()) return false;
      if (hasFormatId()) {
        if (!getFormatId()
            .equals(other.getFormatId())) return false;
      }
      if (hasContentLength() != other.hasContentLength()) return false;
      if (hasContentLength()) {
        if (getContentLength()
            != other.getContentLength()) return false;
      }
      if (hasTimeRange() != other.hasTimeRange()) return false;
      if (hasTimeRange()) {
        if (!getTimeRange()
            .equals(other.getTimeRange())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeaderId()) {
        hash = (37 * hash) + HEADER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getHeaderId();
      }
      if (hasVideoId()) {
        hash = (37 * hash) + VIDEO_ID_FIELD_NUMBER;
        hash = (53 * hash) + getVideoId().hashCode();
      }
      if (hasItag()) {
        hash = (37 * hash) + ITAG_FIELD_NUMBER;
        hash = (53 * hash) + getItag();
      }
      if (hasLmt()) {
        hash = (37 * hash) + LMT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLmt());
      }
      if (hasXtags()) {
        hash = (37 * hash) + XTAGS_FIELD_NUMBER;
        hash = (53 * hash) + getXtags().hashCode();
      }
      if (hasStartRange()) {
        hash = (37 * hash) + START_RANGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartRange());
      }
      if (hasCompressionAlgorithm()) {
        hash = (37 * hash) + COMPRESSION_ALGORITHM_FIELD_NUMBER;
        hash = (53 * hash) + compressionAlgorithm_;
      }
      if (hasIsInitSeg()) {
        hash = (37 * hash) + IS_INIT_SEG_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsInitSeg());
      }
      if (hasSequenceNumber()) {
        hash = (37 * hash) + SEQUENCE_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSequenceNumber());
      }
      if (hasField10()) {
        hash = (37 * hash) + FIELD10_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getField10());
      }
      if (hasStartMs()) {
        hash = (37 * hash) + START_MS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartMs());
      }
      if (hasDurationMs()) {
        hash = (37 * hash) + DURATION_MS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDurationMs());
      }
      if (hasFormatId()) {
        hash = (37 * hash) + FORMAT_ID_FIELD_NUMBER;
        hash = (53 * hash) + getFormatId().hashCode();
      }
      if (hasContentLength()) {
        hash = (37 * hash) + CONTENT_LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getContentLength());
      }
      if (hasTimeRange()) {
        hash = (37 * hash) + TIME_RANGE_FIELD_NUMBER;
        hash = (53 * hash) + getTimeRange().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code video_streaming.MediaHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:video_streaming.MediaHeader)
        dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.lavalink.youtube.protos.MediaHeaderOuterClass.internal_static_video_streaming_MediaHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.lavalink.youtube.protos.MediaHeaderOuterClass.internal_static_video_streaming_MediaHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.class, dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.Builder.class);
      }

      // Construct using dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFormatIdFieldBuilder();
          getTimeRangeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        headerId_ = 0;
        videoId_ = "";
        itag_ = 0;
        lmt_ = 0L;
        xtags_ = "";
        startRange_ = 0L;
        compressionAlgorithm_ = 0;
        isInitSeg_ = false;
        sequenceNumber_ = 0L;
        field10_ = 0L;
        startMs_ = 0L;
        durationMs_ = 0L;
        formatId_ = null;
        if (formatIdBuilder_ != null) {
          formatIdBuilder_.dispose();
          formatIdBuilder_ = null;
        }
        contentLength_ = 0L;
        timeRange_ = null;
        if (timeRangeBuilder_ != null) {
          timeRangeBuilder_.dispose();
          timeRangeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.lavalink.youtube.protos.MediaHeaderOuterClass.internal_static_video_streaming_MediaHeader_descriptor;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader getDefaultInstanceForType() {
        return dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.getDefaultInstance();
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader build() {
        dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader buildPartial() {
        dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader result = new dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.headerId_ = headerId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.videoId_ = videoId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.itag_ = itag_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.lmt_ = lmt_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.xtags_ = xtags_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.startRange_ = startRange_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.compressionAlgorithm_ = compressionAlgorithm_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.isInitSeg_ = isInitSeg_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.sequenceNumber_ = sequenceNumber_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.field10_ = field10_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.startMs_ = startMs_;
          to_bitField0_ |= 0x00000400;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.durationMs_ = durationMs_;
          to_bitField0_ |= 0x00000800;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.formatId_ = formatIdBuilder_ == null
              ? formatId_
              : formatIdBuilder_.build();
          to_bitField0_ |= 0x00001000;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.contentLength_ = contentLength_;
          to_bitField0_ |= 0x00002000;
        }
        if (((from_bitField0_ & 0x00004000) != 0)) {
          result.timeRange_ = timeRangeBuilder_ == null
              ? timeRange_
              : timeRangeBuilder_.build();
          to_bitField0_ |= 0x00004000;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader) {
          return mergeFrom((dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader other) {
        if (other == dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.getDefaultInstance()) return this;
        if (other.hasHeaderId()) {
          setHeaderId(other.getHeaderId());
        }
        if (other.hasVideoId()) {
          videoId_ = other.videoId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasItag()) {
          setItag(other.getItag());
        }
        if (other.hasLmt()) {
          setLmt(other.getLmt());
        }
        if (other.hasXtags()) {
          xtags_ = other.xtags_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasStartRange()) {
          setStartRange(other.getStartRange());
        }
        if (other.hasCompressionAlgorithm()) {
          setCompressionAlgorithm(other.getCompressionAlgorithm());
        }
        if (other.hasIsInitSeg()) {
          setIsInitSeg(other.getIsInitSeg());
        }
        if (other.hasSequenceNumber()) {
          setSequenceNumber(other.getSequenceNumber());
        }
        if (other.hasField10()) {
          setField10(other.getField10());
        }
        if (other.hasStartMs()) {
          setStartMs(other.getStartMs());
        }
        if (other.hasDurationMs()) {
          setDurationMs(other.getDurationMs());
        }
        if (other.hasFormatId()) {
          mergeFormatId(other.getFormatId());
        }
        if (other.hasContentLength()) {
          setContentLength(other.getContentLength());
        }
        if (other.hasTimeRange()) {
          mergeTimeRange(other.getTimeRange());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                headerId_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                videoId_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                itag_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                lmt_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                xtags_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                startRange_ = input.readInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                int tmpRaw = input.readEnum();
                dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.CompressionAlgorithm tmpValue =
                    dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.CompressionAlgorithm.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(7, tmpRaw);
                } else {
                  compressionAlgorithm_ = tmpRaw;
                  bitField0_ |= 0x00000040;
                }
                break;
              } // case 56
              case 64: {
                isInitSeg_ = input.readBool();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                sequenceNumber_ = input.readInt64();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 80: {
                field10_ = input.readInt64();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              case 88: {
                startMs_ = input.readInt64();
                bitField0_ |= 0x00000400;
                break;
              } // case 88
              case 96: {
                durationMs_ = input.readInt64();
                bitField0_ |= 0x00000800;
                break;
              } // case 96
              case 106: {
                input.readMessage(
                    getFormatIdFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00001000;
                break;
              } // case 106
              case 112: {
                contentLength_ = input.readInt64();
                bitField0_ |= 0x00002000;
                break;
              } // case 112
              case 122: {
                input.readMessage(
                    getTimeRangeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00004000;
                break;
              } // case 122
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int headerId_ ;
      /**
       * <code>optional uint32 header_id = 1;</code>
       * @return Whether the headerId field is set.
       */
      @java.lang.Override
      public boolean hasHeaderId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 header_id = 1;</code>
       * @return The headerId.
       */
      @java.lang.Override
      public int getHeaderId() {
        return headerId_;
      }
      /**
       * <code>optional uint32 header_id = 1;</code>
       * @param value The headerId to set.
       * @return This builder for chaining.
       */
      public Builder setHeaderId(int value) {
        
        headerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 header_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeaderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        headerId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object videoId_ = "";
      /**
       * <code>optional string video_id = 2;</code>
       * @return Whether the videoId field is set.
       */
      public boolean hasVideoId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string video_id = 2;</code>
       * @return The videoId.
       */
      public java.lang.String getVideoId() {
        java.lang.Object ref = videoId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            videoId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string video_id = 2;</code>
       * @return The bytes for videoId.
       */
      public com.google.protobuf.ByteString
          getVideoIdBytes() {
        java.lang.Object ref = videoId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          videoId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string video_id = 2;</code>
       * @param value The videoId to set.
       * @return This builder for chaining.
       */
      public Builder setVideoId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        videoId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string video_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVideoId() {
        videoId_ = getDefaultInstance().getVideoId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string video_id = 2;</code>
       * @param value The bytes for videoId to set.
       * @return This builder for chaining.
       */
      public Builder setVideoIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        videoId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int itag_ ;
      /**
       * <code>optional int32 itag = 3;</code>
       * @return Whether the itag field is set.
       */
      @java.lang.Override
      public boolean hasItag() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 itag = 3;</code>
       * @return The itag.
       */
      @java.lang.Override
      public int getItag() {
        return itag_;
      }
      /**
       * <code>optional int32 itag = 3;</code>
       * @param value The itag to set.
       * @return This builder for chaining.
       */
      public Builder setItag(int value) {
        
        itag_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 itag = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearItag() {
        bitField0_ = (bitField0_ & ~0x00000004);
        itag_ = 0;
        onChanged();
        return this;
      }

      private long lmt_ ;
      /**
       * <code>optional uint64 lmt = 4;</code>
       * @return Whether the lmt field is set.
       */
      @java.lang.Override
      public boolean hasLmt() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint64 lmt = 4;</code>
       * @return The lmt.
       */
      @java.lang.Override
      public long getLmt() {
        return lmt_;
      }
      /**
       * <code>optional uint64 lmt = 4;</code>
       * @param value The lmt to set.
       * @return This builder for chaining.
       */
      public Builder setLmt(long value) {
        
        lmt_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 lmt = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLmt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lmt_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object xtags_ = "";
      /**
       * <code>optional string xtags = 5;</code>
       * @return Whether the xtags field is set.
       */
      public boolean hasXtags() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string xtags = 5;</code>
       * @return The xtags.
       */
      public java.lang.String getXtags() {
        java.lang.Object ref = xtags_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            xtags_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string xtags = 5;</code>
       * @return The bytes for xtags.
       */
      public com.google.protobuf.ByteString
          getXtagsBytes() {
        java.lang.Object ref = xtags_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          xtags_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string xtags = 5;</code>
       * @param value The xtags to set.
       * @return This builder for chaining.
       */
      public Builder setXtags(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        xtags_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional string xtags = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearXtags() {
        xtags_ = getDefaultInstance().getXtags();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>optional string xtags = 5;</code>
       * @param value The bytes for xtags to set.
       * @return This builder for chaining.
       */
      public Builder setXtagsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        xtags_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private long startRange_ ;
      /**
       * <code>optional int64 start_range = 6;</code>
       * @return Whether the startRange field is set.
       */
      @java.lang.Override
      public boolean hasStartRange() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int64 start_range = 6;</code>
       * @return The startRange.
       */
      @java.lang.Override
      public long getStartRange() {
        return startRange_;
      }
      /**
       * <code>optional int64 start_range = 6;</code>
       * @param value The startRange to set.
       * @return This builder for chaining.
       */
      public Builder setStartRange(long value) {
        
        startRange_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 start_range = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartRange() {
        bitField0_ = (bitField0_ & ~0x00000020);
        startRange_ = 0L;
        onChanged();
        return this;
      }

      private int compressionAlgorithm_ = 0;
      /**
       * <code>optional .video_streaming.MediaHeader.CompressionAlgorithm compression_algorithm = 7;</code>
       * @return Whether the compressionAlgorithm field is set.
       */
      @java.lang.Override public boolean hasCompressionAlgorithm() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional .video_streaming.MediaHeader.CompressionAlgorithm compression_algorithm = 7;</code>
       * @return The compressionAlgorithm.
       */
      @java.lang.Override
      public dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.CompressionAlgorithm getCompressionAlgorithm() {
        dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.CompressionAlgorithm result = dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.CompressionAlgorithm.forNumber(compressionAlgorithm_);
        return result == null ? dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.CompressionAlgorithm.UNKNOWN : result;
      }
      /**
       * <code>optional .video_streaming.MediaHeader.CompressionAlgorithm compression_algorithm = 7;</code>
       * @param value The compressionAlgorithm to set.
       * @return This builder for chaining.
       */
      public Builder setCompressionAlgorithm(dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader.CompressionAlgorithm value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        compressionAlgorithm_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.MediaHeader.CompressionAlgorithm compression_algorithm = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompressionAlgorithm() {
        bitField0_ = (bitField0_ & ~0x00000040);
        compressionAlgorithm_ = 0;
        onChanged();
        return this;
      }

      private boolean isInitSeg_ ;
      /**
       * <code>optional bool is_init_seg = 8;</code>
       * @return Whether the isInitSeg field is set.
       */
      @java.lang.Override
      public boolean hasIsInitSeg() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional bool is_init_seg = 8;</code>
       * @return The isInitSeg.
       */
      @java.lang.Override
      public boolean getIsInitSeg() {
        return isInitSeg_;
      }
      /**
       * <code>optional bool is_init_seg = 8;</code>
       * @param value The isInitSeg to set.
       * @return This builder for chaining.
       */
      public Builder setIsInitSeg(boolean value) {
        
        isInitSeg_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_init_seg = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsInitSeg() {
        bitField0_ = (bitField0_ & ~0x00000080);
        isInitSeg_ = false;
        onChanged();
        return this;
      }

      private long sequenceNumber_ ;
      /**
       * <code>optional int64 sequence_number = 9;</code>
       * @return Whether the sequenceNumber field is set.
       */
      @java.lang.Override
      public boolean hasSequenceNumber() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional int64 sequence_number = 9;</code>
       * @return The sequenceNumber.
       */
      @java.lang.Override
      public long getSequenceNumber() {
        return sequenceNumber_;
      }
      /**
       * <code>optional int64 sequence_number = 9;</code>
       * @param value The sequenceNumber to set.
       * @return This builder for chaining.
       */
      public Builder setSequenceNumber(long value) {
        
        sequenceNumber_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sequence_number = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequenceNumber() {
        bitField0_ = (bitField0_ & ~0x00000100);
        sequenceNumber_ = 0L;
        onChanged();
        return this;
      }

      private long field10_ ;
      /**
       * <code>optional int64 field10 = 10;</code>
       * @return Whether the field10 field is set.
       */
      @java.lang.Override
      public boolean hasField10() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional int64 field10 = 10;</code>
       * @return The field10.
       */
      @java.lang.Override
      public long getField10() {
        return field10_;
      }
      /**
       * <code>optional int64 field10 = 10;</code>
       * @param value The field10 to set.
       * @return This builder for chaining.
       */
      public Builder setField10(long value) {
        
        field10_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 field10 = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearField10() {
        bitField0_ = (bitField0_ & ~0x00000200);
        field10_ = 0L;
        onChanged();
        return this;
      }

      private long startMs_ ;
      /**
       * <code>optional int64 start_ms = 11;</code>
       * @return Whether the startMs field is set.
       */
      @java.lang.Override
      public boolean hasStartMs() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>optional int64 start_ms = 11;</code>
       * @return The startMs.
       */
      @java.lang.Override
      public long getStartMs() {
        return startMs_;
      }
      /**
       * <code>optional int64 start_ms = 11;</code>
       * @param value The startMs to set.
       * @return This builder for chaining.
       */
      public Builder setStartMs(long value) {
        
        startMs_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 start_ms = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartMs() {
        bitField0_ = (bitField0_ & ~0x00000400);
        startMs_ = 0L;
        onChanged();
        return this;
      }

      private long durationMs_ ;
      /**
       * <code>optional int64 duration_ms = 12;</code>
       * @return Whether the durationMs field is set.
       */
      @java.lang.Override
      public boolean hasDurationMs() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>optional int64 duration_ms = 12;</code>
       * @return The durationMs.
       */
      @java.lang.Override
      public long getDurationMs() {
        return durationMs_;
      }
      /**
       * <code>optional int64 duration_ms = 12;</code>
       * @param value The durationMs to set.
       * @return This builder for chaining.
       */
      public Builder setDurationMs(long value) {
        
        durationMs_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 duration_ms = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearDurationMs() {
        bitField0_ = (bitField0_ & ~0x00000800);
        durationMs_ = 0L;
        onChanged();
        return this;
      }

      private dev.lavalink.youtube.protos.Common.FormatId formatId_;
      private com.google.protobuf.SingleFieldBuilderV3<
          dev.lavalink.youtube.protos.Common.FormatId, dev.lavalink.youtube.protos.Common.FormatId.Builder, dev.lavalink.youtube.protos.Common.FormatIdOrBuilder> formatIdBuilder_;
      /**
       * <code>optional .misc.FormatId format_id = 13;</code>
       * @return Whether the formatId field is set.
       */
      public boolean hasFormatId() {
        return ((bitField0_ & 0x00001000) != 0);
      }
      /**
       * <code>optional .misc.FormatId format_id = 13;</code>
       * @return The formatId.
       */
      public dev.lavalink.youtube.protos.Common.FormatId getFormatId() {
        if (formatIdBuilder_ == null) {
          return formatId_ == null ? dev.lavalink.youtube.protos.Common.FormatId.getDefaultInstance() : formatId_;
        } else {
          return formatIdBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .misc.FormatId format_id = 13;</code>
       */
      public Builder setFormatId(dev.lavalink.youtube.protos.Common.FormatId value) {
        if (formatIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          formatId_ = value;
        } else {
          formatIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>optional .misc.FormatId format_id = 13;</code>
       */
      public Builder setFormatId(
          dev.lavalink.youtube.protos.Common.FormatId.Builder builderForValue) {
        if (formatIdBuilder_ == null) {
          formatId_ = builderForValue.build();
        } else {
          formatIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>optional .misc.FormatId format_id = 13;</code>
       */
      public Builder mergeFormatId(dev.lavalink.youtube.protos.Common.FormatId value) {
        if (formatIdBuilder_ == null) {
          if (((bitField0_ & 0x00001000) != 0) &&
            formatId_ != null &&
            formatId_ != dev.lavalink.youtube.protos.Common.FormatId.getDefaultInstance()) {
            getFormatIdBuilder().mergeFrom(value);
          } else {
            formatId_ = value;
          }
        } else {
          formatIdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>optional .misc.FormatId format_id = 13;</code>
       */
      public Builder clearFormatId() {
        bitField0_ = (bitField0_ & ~0x00001000);
        formatId_ = null;
        if (formatIdBuilder_ != null) {
          formatIdBuilder_.dispose();
          formatIdBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .misc.FormatId format_id = 13;</code>
       */
      public dev.lavalink.youtube.protos.Common.FormatId.Builder getFormatIdBuilder() {
        bitField0_ |= 0x00001000;
        onChanged();
        return getFormatIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .misc.FormatId format_id = 13;</code>
       */
      public dev.lavalink.youtube.protos.Common.FormatIdOrBuilder getFormatIdOrBuilder() {
        if (formatIdBuilder_ != null) {
          return formatIdBuilder_.getMessageOrBuilder();
        } else {
          return formatId_ == null ?
              dev.lavalink.youtube.protos.Common.FormatId.getDefaultInstance() : formatId_;
        }
      }
      /**
       * <code>optional .misc.FormatId format_id = 13;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          dev.lavalink.youtube.protos.Common.FormatId, dev.lavalink.youtube.protos.Common.FormatId.Builder, dev.lavalink.youtube.protos.Common.FormatIdOrBuilder> 
          getFormatIdFieldBuilder() {
        if (formatIdBuilder_ == null) {
          formatIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              dev.lavalink.youtube.protos.Common.FormatId, dev.lavalink.youtube.protos.Common.FormatId.Builder, dev.lavalink.youtube.protos.Common.FormatIdOrBuilder>(
                  getFormatId(),
                  getParentForChildren(),
                  isClean());
          formatId_ = null;
        }
        return formatIdBuilder_;
      }

      private long contentLength_ ;
      /**
       * <code>optional int64 content_length = 14;</code>
       * @return Whether the contentLength field is set.
       */
      @java.lang.Override
      public boolean hasContentLength() {
        return ((bitField0_ & 0x00002000) != 0);
      }
      /**
       * <code>optional int64 content_length = 14;</code>
       * @return The contentLength.
       */
      @java.lang.Override
      public long getContentLength() {
        return contentLength_;
      }
      /**
       * <code>optional int64 content_length = 14;</code>
       * @param value The contentLength to set.
       * @return This builder for chaining.
       */
      public Builder setContentLength(long value) {
        
        contentLength_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 content_length = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearContentLength() {
        bitField0_ = (bitField0_ & ~0x00002000);
        contentLength_ = 0L;
        onChanged();
        return this;
      }

      private dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange timeRange_;
      private com.google.protobuf.SingleFieldBuilderV3<
          dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange, dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange.Builder, dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRangeOrBuilder> timeRangeBuilder_;
      /**
       * <code>optional .video_streaming.TimeRange time_range = 15;</code>
       * @return Whether the timeRange field is set.
       */
      public boolean hasTimeRange() {
        return ((bitField0_ & 0x00004000) != 0);
      }
      /**
       * <code>optional .video_streaming.TimeRange time_range = 15;</code>
       * @return The timeRange.
       */
      public dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange getTimeRange() {
        if (timeRangeBuilder_ == null) {
          return timeRange_ == null ? dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange.getDefaultInstance() : timeRange_;
        } else {
          return timeRangeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .video_streaming.TimeRange time_range = 15;</code>
       */
      public Builder setTimeRange(dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange value) {
        if (timeRangeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timeRange_ = value;
        } else {
          timeRangeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.TimeRange time_range = 15;</code>
       */
      public Builder setTimeRange(
          dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange.Builder builderForValue) {
        if (timeRangeBuilder_ == null) {
          timeRange_ = builderForValue.build();
        } else {
          timeRangeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.TimeRange time_range = 15;</code>
       */
      public Builder mergeTimeRange(dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange value) {
        if (timeRangeBuilder_ == null) {
          if (((bitField0_ & 0x00004000) != 0) &&
            timeRange_ != null &&
            timeRange_ != dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange.getDefaultInstance()) {
            getTimeRangeBuilder().mergeFrom(value);
          } else {
            timeRange_ = value;
          }
        } else {
          timeRangeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.TimeRange time_range = 15;</code>
       */
      public Builder clearTimeRange() {
        bitField0_ = (bitField0_ & ~0x00004000);
        timeRange_ = null;
        if (timeRangeBuilder_ != null) {
          timeRangeBuilder_.dispose();
          timeRangeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.TimeRange time_range = 15;</code>
       */
      public dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange.Builder getTimeRangeBuilder() {
        bitField0_ |= 0x00004000;
        onChanged();
        return getTimeRangeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .video_streaming.TimeRange time_range = 15;</code>
       */
      public dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRangeOrBuilder getTimeRangeOrBuilder() {
        if (timeRangeBuilder_ != null) {
          return timeRangeBuilder_.getMessageOrBuilder();
        } else {
          return timeRange_ == null ?
              dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange.getDefaultInstance() : timeRange_;
        }
      }
      /**
       * <code>optional .video_streaming.TimeRange time_range = 15;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange, dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange.Builder, dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRangeOrBuilder> 
          getTimeRangeFieldBuilder() {
        if (timeRangeBuilder_ == null) {
          timeRangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange, dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRange.Builder, dev.lavalink.youtube.protos.TimeRangeOuterClass.TimeRangeOrBuilder>(
                  getTimeRange(),
                  getParentForChildren(),
                  isClean());
          timeRange_ = null;
        }
        return timeRangeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:video_streaming.MediaHeader)
    }

    // @@protoc_insertion_point(class_scope:video_streaming.MediaHeader)
    private static final dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader();
    }

    public static dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MediaHeader>
        PARSER = new com.google.protobuf.AbstractParser<MediaHeader>() {
      @java.lang.Override
      public MediaHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MediaHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MediaHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.lavalink.youtube.protos.MediaHeaderOuterClass.MediaHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_video_streaming_MediaHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_video_streaming_MediaHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"video_streaming/media_header.proto\022\017vi" +
      "deo_streaming\032\021misc/common.proto\032 video_" +
      "streaming/time_range.proto\"\315\003\n\013MediaHead" +
      "er\022\021\n\theader_id\030\001 \001(\r\022\020\n\010video_id\030\002 \001(\t\022" +
      "\014\n\004itag\030\003 \001(\005\022\013\n\003lmt\030\004 \001(\004\022\r\n\005xtags\030\005 \001(" +
      "\t\022\023\n\013start_range\030\006 \001(\003\022P\n\025compression_al" +
      "gorithm\030\007 \001(\01621.video_streaming.MediaHea" +
      "der.CompressionAlgorithm\022\023\n\013is_init_seg\030" +
      "\010 \001(\010\022\027\n\017sequence_number\030\t \001(\003\022\017\n\007field1" +
      "0\030\n \001(\003\022\020\n\010start_ms\030\013 \001(\003\022\023\n\013duration_ms" +
      "\030\014 \001(\003\022!\n\tformat_id\030\r \001(\0132\016.misc.FormatI" +
      "d\022\026\n\016content_length\030\016 \001(\003\022.\n\ntime_range\030" +
      "\017 \001(\0132\032.video_streaming.TimeRange\"7\n\024Com" +
      "pressionAlgorithm\022\013\n\007UNKNOWN\020\000\022\010\n\004NONE\020\001" +
      "\022\010\n\004GZIP\020\002B\035\n\033dev.lavalink.youtube.proto" +
      "s"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          dev.lavalink.youtube.protos.Common.getDescriptor(),
          dev.lavalink.youtube.protos.TimeRangeOuterClass.getDescriptor(),
        });
    internal_static_video_streaming_MediaHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_video_streaming_MediaHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_video_streaming_MediaHeader_descriptor,
        new java.lang.String[] { "HeaderId", "VideoId", "Itag", "Lmt", "Xtags", "StartRange", "CompressionAlgorithm", "IsInitSeg", "SequenceNumber", "Field10", "StartMs", "DurationMs", "FormatId", "ContentLength", "TimeRange", });
    dev.lavalink.youtube.protos.Common.getDescriptor();
    dev.lavalink.youtube.protos.TimeRangeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
