// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_streaming/onesie_header_type.proto

package dev.lavalink.youtube.protos;

public final class OnesieHeaderTypeOuterClass {
  private OnesieHeaderTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code video_streaming.OnesieHeaderType}
   */
  public enum OnesieHeaderType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ONESIE_PLAYER_RESPONSE = 0;</code>
     */
    ONESIE_PLAYER_RESPONSE(0),
    /**
     * <code>MEDIA = 1;</code>
     */
    MEDIA(1),
    /**
     * <code>MEDIA_DECRYPTION_KEY = 2;</code>
     */
    MEDIA_DECRYPTION_KEY(2),
    /**
     * <code>CLEAR_MEDIA = 3;</code>
     */
    CLEAR_MEDIA(3),
    /**
     * <code>CLEAR_INIT_SEGMENT = 4;</code>
     */
    CLEAR_INIT_SEGMENT(4),
    /**
     * <code>ACK = 5;</code>
     */
    ACK(5),
    /**
     * <code>MEDIA_STREAMER_HOSTNAME = 6;</code>
     */
    MEDIA_STREAMER_HOSTNAME(6),
    /**
     * <code>MEDIA_SIZE_HINT = 7;</code>
     */
    MEDIA_SIZE_HINT(7),
    /**
     * <code>PLAYER_SERVICE_RESPONSE_PUSH_URL = 8;</code>
     */
    PLAYER_SERVICE_RESPONSE_PUSH_URL(8),
    /**
     * <code>LAST_HIGH_PRIORITY_HINT = 9;</code>
     */
    LAST_HIGH_PRIORITY_HINT(9),
    /**
     * <code>STREAM_METADATA = 16;</code>
     */
    STREAM_METADATA(16),
    /**
     * <code>ENCRYPTED_INNERTUBE_RESPONSE_PART = 25;</code>
     */
    ENCRYPTED_INNERTUBE_RESPONSE_PART(25),
    ;

    /**
     * <code>ONESIE_PLAYER_RESPONSE = 0;</code>
     */
    public static final int ONESIE_PLAYER_RESPONSE_VALUE = 0;
    /**
     * <code>MEDIA = 1;</code>
     */
    public static final int MEDIA_VALUE = 1;
    /**
     * <code>MEDIA_DECRYPTION_KEY = 2;</code>
     */
    public static final int MEDIA_DECRYPTION_KEY_VALUE = 2;
    /**
     * <code>CLEAR_MEDIA = 3;</code>
     */
    public static final int CLEAR_MEDIA_VALUE = 3;
    /**
     * <code>CLEAR_INIT_SEGMENT = 4;</code>
     */
    public static final int CLEAR_INIT_SEGMENT_VALUE = 4;
    /**
     * <code>ACK = 5;</code>
     */
    public static final int ACK_VALUE = 5;
    /**
     * <code>MEDIA_STREAMER_HOSTNAME = 6;</code>
     */
    public static final int MEDIA_STREAMER_HOSTNAME_VALUE = 6;
    /**
     * <code>MEDIA_SIZE_HINT = 7;</code>
     */
    public static final int MEDIA_SIZE_HINT_VALUE = 7;
    /**
     * <code>PLAYER_SERVICE_RESPONSE_PUSH_URL = 8;</code>
     */
    public static final int PLAYER_SERVICE_RESPONSE_PUSH_URL_VALUE = 8;
    /**
     * <code>LAST_HIGH_PRIORITY_HINT = 9;</code>
     */
    public static final int LAST_HIGH_PRIORITY_HINT_VALUE = 9;
    /**
     * <code>STREAM_METADATA = 16;</code>
     */
    public static final int STREAM_METADATA_VALUE = 16;
    /**
     * <code>ENCRYPTED_INNERTUBE_RESPONSE_PART = 25;</code>
     */
    public static final int ENCRYPTED_INNERTUBE_RESPONSE_PART_VALUE = 25;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OnesieHeaderType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OnesieHeaderType forNumber(int value) {
      switch (value) {
        case 0: return ONESIE_PLAYER_RESPONSE;
        case 1: return MEDIA;
        case 2: return MEDIA_DECRYPTION_KEY;
        case 3: return CLEAR_MEDIA;
        case 4: return CLEAR_INIT_SEGMENT;
        case 5: return ACK;
        case 6: return MEDIA_STREAMER_HOSTNAME;
        case 7: return MEDIA_SIZE_HINT;
        case 8: return PLAYER_SERVICE_RESPONSE_PUSH_URL;
        case 9: return LAST_HIGH_PRIORITY_HINT;
        case 16: return STREAM_METADATA;
        case 25: return ENCRYPTED_INNERTUBE_RESPONSE_PART;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OnesieHeaderType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OnesieHeaderType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OnesieHeaderType>() {
            public OnesieHeaderType findValueByNumber(int number) {
              return OnesieHeaderType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dev.lavalink.youtube.protos.OnesieHeaderTypeOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final OnesieHeaderType[] VALUES = values();

    public static OnesieHeaderType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OnesieHeaderType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:video_streaming.OnesieHeaderType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(video_streaming/onesie_header_type.pro" +
      "to\022\017video_streaming*\266\002\n\020OnesieHeaderType" +
      "\022\032\n\026ONESIE_PLAYER_RESPONSE\020\000\022\t\n\005MEDIA\020\001\022" +
      "\030\n\024MEDIA_DECRYPTION_KEY\020\002\022\017\n\013CLEAR_MEDIA" +
      "\020\003\022\026\n\022CLEAR_INIT_SEGMENT\020\004\022\007\n\003ACK\020\005\022\033\n\027M" +
      "EDIA_STREAMER_HOSTNAME\020\006\022\023\n\017MEDIA_SIZE_H" +
      "INT\020\007\022$\n PLAYER_SERVICE_RESPONSE_PUSH_UR" +
      "L\020\010\022\033\n\027LAST_HIGH_PRIORITY_HINT\020\t\022\023\n\017STRE" +
      "AM_METADATA\020\020\022%\n!ENCRYPTED_INNERTUBE_RES" +
      "PONSE_PART\020\031B\035\n\033dev.lavalink.youtube.pro" +
      "tos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
