// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_streaming/onesie_player_response.proto

package dev.lavalink.youtube.protos;

public final class OnesiePlayerResponseOuterClass {
  private OnesiePlayerResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OnesiePlayerResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:video_streaming.OnesiePlayerResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .video_streaming.OnesieProxyStatus onesie_proxy_status = 1;</code>
     * @return Whether the onesieProxyStatus field is set.
     */
    boolean hasOnesieProxyStatus();
    /**
     * <code>optional .video_streaming.OnesieProxyStatus onesie_proxy_status = 1;</code>
     * @return The onesieProxyStatus.
     */
    dev.lavalink.youtube.protos.OnesieProxyStatusOuterClass.OnesieProxyStatus getOnesieProxyStatus();

    /**
     * <code>optional int32 http_status = 2;</code>
     * @return Whether the httpStatus field is set.
     */
    boolean hasHttpStatus();
    /**
     * <code>optional int32 http_status = 2;</code>
     * @return The httpStatus.
     */
    int getHttpStatus();

    /**
     * <code>repeated .misc.HttpHeader headers = 3;</code>
     */
    java.util.List<dev.lavalink.youtube.protos.Common.HttpHeader> 
        getHeadersList();
    /**
     * <code>repeated .misc.HttpHeader headers = 3;</code>
     */
    dev.lavalink.youtube.protos.Common.HttpHeader getHeaders(int index);
    /**
     * <code>repeated .misc.HttpHeader headers = 3;</code>
     */
    int getHeadersCount();
    /**
     * <code>repeated .misc.HttpHeader headers = 3;</code>
     */
    java.util.List<? extends dev.lavalink.youtube.protos.Common.HttpHeaderOrBuilder> 
        getHeadersOrBuilderList();
    /**
     * <code>repeated .misc.HttpHeader headers = 3;</code>
     */
    dev.lavalink.youtube.protos.Common.HttpHeaderOrBuilder getHeadersOrBuilder(
        int index);

    /**
     * <code>optional bytes body = 4;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <code>optional bytes body = 4;</code>
     * @return The body.
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code video_streaming.OnesiePlayerResponse}
   */
  public static final class OnesiePlayerResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:video_streaming.OnesiePlayerResponse)
      OnesiePlayerResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OnesiePlayerResponse.newBuilder() to construct.
    private OnesiePlayerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OnesiePlayerResponse() {
      onesieProxyStatus_ = 0;
      headers_ = java.util.Collections.emptyList();
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OnesiePlayerResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.internal_static_video_streaming_OnesiePlayerResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.internal_static_video_streaming_OnesiePlayerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse.class, dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse.Builder.class);
    }

    private int bitField0_;
    public static final int ONESIE_PROXY_STATUS_FIELD_NUMBER = 1;
    private int onesieProxyStatus_ = 0;
    /**
     * <code>optional .video_streaming.OnesieProxyStatus onesie_proxy_status = 1;</code>
     * @return Whether the onesieProxyStatus field is set.
     */
    @java.lang.Override public boolean hasOnesieProxyStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .video_streaming.OnesieProxyStatus onesie_proxy_status = 1;</code>
     * @return The onesieProxyStatus.
     */
    @java.lang.Override public dev.lavalink.youtube.protos.OnesieProxyStatusOuterClass.OnesieProxyStatus getOnesieProxyStatus() {
      dev.lavalink.youtube.protos.OnesieProxyStatusOuterClass.OnesieProxyStatus result = dev.lavalink.youtube.protos.OnesieProxyStatusOuterClass.OnesieProxyStatus.forNumber(onesieProxyStatus_);
      return result == null ? dev.lavalink.youtube.protos.OnesieProxyStatusOuterClass.OnesieProxyStatus.ONESIE_PROXY_STATUS_UNKNOWN : result;
    }

    public static final int HTTP_STATUS_FIELD_NUMBER = 2;
    private int httpStatus_ = 0;
    /**
     * <code>optional int32 http_status = 2;</code>
     * @return Whether the httpStatus field is set.
     */
    @java.lang.Override
    public boolean hasHttpStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 http_status = 2;</code>
     * @return The httpStatus.
     */
    @java.lang.Override
    public int getHttpStatus() {
      return httpStatus_;
    }

    public static final int HEADERS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<dev.lavalink.youtube.protos.Common.HttpHeader> headers_;
    /**
     * <code>repeated .misc.HttpHeader headers = 3;</code>
     */
    @java.lang.Override
    public java.util.List<dev.lavalink.youtube.protos.Common.HttpHeader> getHeadersList() {
      return headers_;
    }
    /**
     * <code>repeated .misc.HttpHeader headers = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends dev.lavalink.youtube.protos.Common.HttpHeaderOrBuilder> 
        getHeadersOrBuilderList() {
      return headers_;
    }
    /**
     * <code>repeated .misc.HttpHeader headers = 3;</code>
     */
    @java.lang.Override
    public int getHeadersCount() {
      return headers_.size();
    }
    /**
     * <code>repeated .misc.HttpHeader headers = 3;</code>
     */
    @java.lang.Override
    public dev.lavalink.youtube.protos.Common.HttpHeader getHeaders(int index) {
      return headers_.get(index);
    }
    /**
     * <code>repeated .misc.HttpHeader headers = 3;</code>
     */
    @java.lang.Override
    public dev.lavalink.youtube.protos.Common.HttpHeaderOrBuilder getHeadersOrBuilder(
        int index) {
      return headers_.get(index);
    }

    public static final int BODY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes body = 4;</code>
     * @return Whether the body field is set.
     */
    @java.lang.Override
    public boolean hasBody() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes body = 4;</code>
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, onesieProxyStatus_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, httpStatus_);
      }
      for (int i = 0; i < headers_.size(); i++) {
        output.writeMessage(3, headers_.get(i));
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(4, body_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, onesieProxyStatus_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, httpStatus_);
      }
      for (int i = 0; i < headers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, headers_.get(i));
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse)) {
        return super.equals(obj);
      }
      dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse other = (dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse) obj;

      if (hasOnesieProxyStatus() != other.hasOnesieProxyStatus()) return false;
      if (hasOnesieProxyStatus()) {
        if (onesieProxyStatus_ != other.onesieProxyStatus_) return false;
      }
      if (hasHttpStatus() != other.hasHttpStatus()) return false;
      if (hasHttpStatus()) {
        if (getHttpStatus()
            != other.getHttpStatus()) return false;
      }
      if (!getHeadersList()
          .equals(other.getHeadersList())) return false;
      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOnesieProxyStatus()) {
        hash = (37 * hash) + ONESIE_PROXY_STATUS_FIELD_NUMBER;
        hash = (53 * hash) + onesieProxyStatus_;
      }
      if (hasHttpStatus()) {
        hash = (37 * hash) + HTTP_STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getHttpStatus();
      }
      if (getHeadersCount() > 0) {
        hash = (37 * hash) + HEADERS_FIELD_NUMBER;
        hash = (53 * hash) + getHeadersList().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code video_streaming.OnesiePlayerResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:video_streaming.OnesiePlayerResponse)
        dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.internal_static_video_streaming_OnesiePlayerResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.internal_static_video_streaming_OnesiePlayerResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse.class, dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse.Builder.class);
      }

      // Construct using dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        onesieProxyStatus_ = 0;
        httpStatus_ = 0;
        if (headersBuilder_ == null) {
          headers_ = java.util.Collections.emptyList();
        } else {
          headers_ = null;
          headersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        body_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.internal_static_video_streaming_OnesiePlayerResponse_descriptor;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse getDefaultInstanceForType() {
        return dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse.getDefaultInstance();
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse build() {
        dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse buildPartial() {
        dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse result = new dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse result) {
        if (headersBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            headers_ = java.util.Collections.unmodifiableList(headers_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.headers_ = headers_;
        } else {
          result.headers_ = headersBuilder_.build();
        }
      }

      private void buildPartial0(dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.onesieProxyStatus_ = onesieProxyStatus_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.httpStatus_ = httpStatus_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.body_ = body_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse) {
          return mergeFrom((dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse other) {
        if (other == dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse.getDefaultInstance()) return this;
        if (other.hasOnesieProxyStatus()) {
          setOnesieProxyStatus(other.getOnesieProxyStatus());
        }
        if (other.hasHttpStatus()) {
          setHttpStatus(other.getHttpStatus());
        }
        if (headersBuilder_ == null) {
          if (!other.headers_.isEmpty()) {
            if (headers_.isEmpty()) {
              headers_ = other.headers_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureHeadersIsMutable();
              headers_.addAll(other.headers_);
            }
            onChanged();
          }
        } else {
          if (!other.headers_.isEmpty()) {
            if (headersBuilder_.isEmpty()) {
              headersBuilder_.dispose();
              headersBuilder_ = null;
              headers_ = other.headers_;
              bitField0_ = (bitField0_ & ~0x00000004);
              headersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHeadersFieldBuilder() : null;
            } else {
              headersBuilder_.addAllMessages(other.headers_);
            }
          }
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int tmpRaw = input.readEnum();
                dev.lavalink.youtube.protos.OnesieProxyStatusOuterClass.OnesieProxyStatus tmpValue =
                    dev.lavalink.youtube.protos.OnesieProxyStatusOuterClass.OnesieProxyStatus.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(1, tmpRaw);
                } else {
                  onesieProxyStatus_ = tmpRaw;
                  bitField0_ |= 0x00000001;
                }
                break;
              } // case 8
              case 16: {
                httpStatus_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                dev.lavalink.youtube.protos.Common.HttpHeader m =
                    input.readMessage(
                        dev.lavalink.youtube.protos.Common.HttpHeader.PARSER,
                        extensionRegistry);
                if (headersBuilder_ == null) {
                  ensureHeadersIsMutable();
                  headers_.add(m);
                } else {
                  headersBuilder_.addMessage(m);
                }
                break;
              } // case 26
              case 34: {
                body_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int onesieProxyStatus_ = 0;
      /**
       * <code>optional .video_streaming.OnesieProxyStatus onesie_proxy_status = 1;</code>
       * @return Whether the onesieProxyStatus field is set.
       */
      @java.lang.Override public boolean hasOnesieProxyStatus() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .video_streaming.OnesieProxyStatus onesie_proxy_status = 1;</code>
       * @return The onesieProxyStatus.
       */
      @java.lang.Override
      public dev.lavalink.youtube.protos.OnesieProxyStatusOuterClass.OnesieProxyStatus getOnesieProxyStatus() {
        dev.lavalink.youtube.protos.OnesieProxyStatusOuterClass.OnesieProxyStatus result = dev.lavalink.youtube.protos.OnesieProxyStatusOuterClass.OnesieProxyStatus.forNumber(onesieProxyStatus_);
        return result == null ? dev.lavalink.youtube.protos.OnesieProxyStatusOuterClass.OnesieProxyStatus.ONESIE_PROXY_STATUS_UNKNOWN : result;
      }
      /**
       * <code>optional .video_streaming.OnesieProxyStatus onesie_proxy_status = 1;</code>
       * @param value The onesieProxyStatus to set.
       * @return This builder for chaining.
       */
      public Builder setOnesieProxyStatus(dev.lavalink.youtube.protos.OnesieProxyStatusOuterClass.OnesieProxyStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        onesieProxyStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.OnesieProxyStatus onesie_proxy_status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOnesieProxyStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        onesieProxyStatus_ = 0;
        onChanged();
        return this;
      }

      private int httpStatus_ ;
      /**
       * <code>optional int32 http_status = 2;</code>
       * @return Whether the httpStatus field is set.
       */
      @java.lang.Override
      public boolean hasHttpStatus() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 http_status = 2;</code>
       * @return The httpStatus.
       */
      @java.lang.Override
      public int getHttpStatus() {
        return httpStatus_;
      }
      /**
       * <code>optional int32 http_status = 2;</code>
       * @param value The httpStatus to set.
       * @return This builder for chaining.
       */
      public Builder setHttpStatus(int value) {
        
        httpStatus_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 http_status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHttpStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        httpStatus_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<dev.lavalink.youtube.protos.Common.HttpHeader> headers_ =
        java.util.Collections.emptyList();
      private void ensureHeadersIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          headers_ = new java.util.ArrayList<dev.lavalink.youtube.protos.Common.HttpHeader>(headers_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          dev.lavalink.youtube.protos.Common.HttpHeader, dev.lavalink.youtube.protos.Common.HttpHeader.Builder, dev.lavalink.youtube.protos.Common.HttpHeaderOrBuilder> headersBuilder_;

      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public java.util.List<dev.lavalink.youtube.protos.Common.HttpHeader> getHeadersList() {
        if (headersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(headers_);
        } else {
          return headersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public int getHeadersCount() {
        if (headersBuilder_ == null) {
          return headers_.size();
        } else {
          return headersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public dev.lavalink.youtube.protos.Common.HttpHeader getHeaders(int index) {
        if (headersBuilder_ == null) {
          return headers_.get(index);
        } else {
          return headersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public Builder setHeaders(
          int index, dev.lavalink.youtube.protos.Common.HttpHeader value) {
        if (headersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeadersIsMutable();
          headers_.set(index, value);
          onChanged();
        } else {
          headersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public Builder setHeaders(
          int index, dev.lavalink.youtube.protos.Common.HttpHeader.Builder builderForValue) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.set(index, builderForValue.build());
          onChanged();
        } else {
          headersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public Builder addHeaders(dev.lavalink.youtube.protos.Common.HttpHeader value) {
        if (headersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeadersIsMutable();
          headers_.add(value);
          onChanged();
        } else {
          headersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public Builder addHeaders(
          int index, dev.lavalink.youtube.protos.Common.HttpHeader value) {
        if (headersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeadersIsMutable();
          headers_.add(index, value);
          onChanged();
        } else {
          headersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public Builder addHeaders(
          dev.lavalink.youtube.protos.Common.HttpHeader.Builder builderForValue) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.add(builderForValue.build());
          onChanged();
        } else {
          headersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public Builder addHeaders(
          int index, dev.lavalink.youtube.protos.Common.HttpHeader.Builder builderForValue) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.add(index, builderForValue.build());
          onChanged();
        } else {
          headersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public Builder addAllHeaders(
          java.lang.Iterable<? extends dev.lavalink.youtube.protos.Common.HttpHeader> values) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, headers_);
          onChanged();
        } else {
          headersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public Builder clearHeaders() {
        if (headersBuilder_ == null) {
          headers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          headersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public Builder removeHeaders(int index) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.remove(index);
          onChanged();
        } else {
          headersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public dev.lavalink.youtube.protos.Common.HttpHeader.Builder getHeadersBuilder(
          int index) {
        return getHeadersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public dev.lavalink.youtube.protos.Common.HttpHeaderOrBuilder getHeadersOrBuilder(
          int index) {
        if (headersBuilder_ == null) {
          return headers_.get(index);  } else {
          return headersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public java.util.List<? extends dev.lavalink.youtube.protos.Common.HttpHeaderOrBuilder> 
           getHeadersOrBuilderList() {
        if (headersBuilder_ != null) {
          return headersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(headers_);
        }
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public dev.lavalink.youtube.protos.Common.HttpHeader.Builder addHeadersBuilder() {
        return getHeadersFieldBuilder().addBuilder(
            dev.lavalink.youtube.protos.Common.HttpHeader.getDefaultInstance());
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public dev.lavalink.youtube.protos.Common.HttpHeader.Builder addHeadersBuilder(
          int index) {
        return getHeadersFieldBuilder().addBuilder(
            index, dev.lavalink.youtube.protos.Common.HttpHeader.getDefaultInstance());
      }
      /**
       * <code>repeated .misc.HttpHeader headers = 3;</code>
       */
      public java.util.List<dev.lavalink.youtube.protos.Common.HttpHeader.Builder> 
           getHeadersBuilderList() {
        return getHeadersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          dev.lavalink.youtube.protos.Common.HttpHeader, dev.lavalink.youtube.protos.Common.HttpHeader.Builder, dev.lavalink.youtube.protos.Common.HttpHeaderOrBuilder> 
          getHeadersFieldBuilder() {
        if (headersBuilder_ == null) {
          headersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              dev.lavalink.youtube.protos.Common.HttpHeader, dev.lavalink.youtube.protos.Common.HttpHeader.Builder, dev.lavalink.youtube.protos.Common.HttpHeaderOrBuilder>(
                  headers_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          headers_ = null;
        }
        return headersBuilder_;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes body = 4;</code>
       * @return Whether the body field is set.
       */
      @java.lang.Override
      public boolean hasBody() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bytes body = 4;</code>
       * @return The body.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>optional bytes body = 4;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        body_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes body = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000008);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:video_streaming.OnesiePlayerResponse)
    }

    // @@protoc_insertion_point(class_scope:video_streaming.OnesiePlayerResponse)
    private static final dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse();
    }

    public static dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<OnesiePlayerResponse>
        PARSER = new com.google.protobuf.AbstractParser<OnesiePlayerResponse>() {
      @java.lang.Override
      public OnesiePlayerResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OnesiePlayerResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OnesiePlayerResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.lavalink.youtube.protos.OnesiePlayerResponseOuterClass.OnesiePlayerResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_video_streaming_OnesiePlayerResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_video_streaming_OnesiePlayerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,video_streaming/onesie_player_response" +
      ".proto\022\017video_streaming\032\021misc/common.pro" +
      "to\032)video_streaming/onesie_proxy_status." +
      "proto\"\235\001\n\024OnesiePlayerResponse\022?\n\023onesie" +
      "_proxy_status\030\001 \001(\0162\".video_streaming.On" +
      "esieProxyStatus\022\023\n\013http_status\030\002 \001(\005\022!\n\007" +
      "headers\030\003 \003(\0132\020.misc.HttpHeader\022\014\n\004body\030" +
      "\004 \001(\014B\035\n\033dev.lavalink.youtube.protos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          dev.lavalink.youtube.protos.Common.getDescriptor(),
          dev.lavalink.youtube.protos.OnesieProxyStatusOuterClass.getDescriptor(),
        });
    internal_static_video_streaming_OnesiePlayerResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_video_streaming_OnesiePlayerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_video_streaming_OnesiePlayerResponse_descriptor,
        new java.lang.String[] { "OnesieProxyStatus", "HttpStatus", "Headers", "Body", });
    dev.lavalink.youtube.protos.Common.getDescriptor();
    dev.lavalink.youtube.protos.OnesieProxyStatusOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
