// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_streaming/playback_start_policy.proto

package dev.lavalink.youtube.protos;

public final class PlaybackStartPolicyOuterClass {
  private PlaybackStartPolicyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlaybackStartPolicyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:video_streaming.PlaybackStartPolicy)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
     * @return Whether the startMinReadaheadPolicy field is set.
     */
    boolean hasStartMinReadaheadPolicy();
    /**
     * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
     * @return The startMinReadaheadPolicy.
     */
    dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy getStartMinReadaheadPolicy();
    /**
     * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
     */
    dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicyOrBuilder getStartMinReadaheadPolicyOrBuilder();

    /**
     * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
     * @return Whether the resumeMinReadaheadPolicy field is set.
     */
    boolean hasResumeMinReadaheadPolicy();
    /**
     * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
     * @return The resumeMinReadaheadPolicy.
     */
    dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy getResumeMinReadaheadPolicy();
    /**
     * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
     */
    dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicyOrBuilder getResumeMinReadaheadPolicyOrBuilder();
  }
  /**
   * Protobuf type {@code video_streaming.PlaybackStartPolicy}
   */
  public static final class PlaybackStartPolicy extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:video_streaming.PlaybackStartPolicy)
      PlaybackStartPolicyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlaybackStartPolicy.newBuilder() to construct.
    private PlaybackStartPolicy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlaybackStartPolicy() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlaybackStartPolicy();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.internal_static_video_streaming_PlaybackStartPolicy_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.internal_static_video_streaming_PlaybackStartPolicy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.class, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.Builder.class);
    }

    public interface ReadaheadPolicyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:video_streaming.PlaybackStartPolicy.ReadaheadPolicy)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 min_readahead_ms = 2;</code>
       * @return Whether the minReadaheadMs field is set.
       */
      boolean hasMinReadaheadMs();
      /**
       * <code>optional int32 min_readahead_ms = 2;</code>
       * @return The minReadaheadMs.
       */
      int getMinReadaheadMs();

      /**
       * <code>optional int32 min_bandwidth_bytes_per_sec = 1;</code>
       * @return Whether the minBandwidthBytesPerSec field is set.
       */
      boolean hasMinBandwidthBytesPerSec();
      /**
       * <code>optional int32 min_bandwidth_bytes_per_sec = 1;</code>
       * @return The minBandwidthBytesPerSec.
       */
      int getMinBandwidthBytesPerSec();
    }
    /**
     * Protobuf type {@code video_streaming.PlaybackStartPolicy.ReadaheadPolicy}
     */
    public static final class ReadaheadPolicy extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:video_streaming.PlaybackStartPolicy.ReadaheadPolicy)
        ReadaheadPolicyOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ReadaheadPolicy.newBuilder() to construct.
      private ReadaheadPolicy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ReadaheadPolicy() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new ReadaheadPolicy();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.internal_static_video_streaming_PlaybackStartPolicy_ReadaheadPolicy_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.internal_static_video_streaming_PlaybackStartPolicy_ReadaheadPolicy_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.class, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.Builder.class);
      }

      private int bitField0_;
      public static final int MIN_READAHEAD_MS_FIELD_NUMBER = 2;
      private int minReadaheadMs_ = 0;
      /**
       * <code>optional int32 min_readahead_ms = 2;</code>
       * @return Whether the minReadaheadMs field is set.
       */
      @java.lang.Override
      public boolean hasMinReadaheadMs() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 min_readahead_ms = 2;</code>
       * @return The minReadaheadMs.
       */
      @java.lang.Override
      public int getMinReadaheadMs() {
        return minReadaheadMs_;
      }

      public static final int MIN_BANDWIDTH_BYTES_PER_SEC_FIELD_NUMBER = 1;
      private int minBandwidthBytesPerSec_ = 0;
      /**
       * <code>optional int32 min_bandwidth_bytes_per_sec = 1;</code>
       * @return Whether the minBandwidthBytesPerSec field is set.
       */
      @java.lang.Override
      public boolean hasMinBandwidthBytesPerSec() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 min_bandwidth_bytes_per_sec = 1;</code>
       * @return The minBandwidthBytesPerSec.
       */
      @java.lang.Override
      public int getMinBandwidthBytesPerSec() {
        return minBandwidthBytesPerSec_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeInt32(1, minBandwidthBytesPerSec_);
        }
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeInt32(2, minReadaheadMs_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, minBandwidthBytesPerSec_);
        }
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, minReadaheadMs_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy)) {
          return super.equals(obj);
        }
        dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy other = (dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy) obj;

        if (hasMinReadaheadMs() != other.hasMinReadaheadMs()) return false;
        if (hasMinReadaheadMs()) {
          if (getMinReadaheadMs()
              != other.getMinReadaheadMs()) return false;
        }
        if (hasMinBandwidthBytesPerSec() != other.hasMinBandwidthBytesPerSec()) return false;
        if (hasMinBandwidthBytesPerSec()) {
          if (getMinBandwidthBytesPerSec()
              != other.getMinBandwidthBytesPerSec()) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasMinReadaheadMs()) {
          hash = (37 * hash) + MIN_READAHEAD_MS_FIELD_NUMBER;
          hash = (53 * hash) + getMinReadaheadMs();
        }
        if (hasMinBandwidthBytesPerSec()) {
          hash = (37 * hash) + MIN_BANDWIDTH_BYTES_PER_SEC_FIELD_NUMBER;
          hash = (53 * hash) + getMinBandwidthBytesPerSec();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code video_streaming.PlaybackStartPolicy.ReadaheadPolicy}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:video_streaming.PlaybackStartPolicy.ReadaheadPolicy)
          dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.internal_static_video_streaming_PlaybackStartPolicy_ReadaheadPolicy_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.internal_static_video_streaming_PlaybackStartPolicy_ReadaheadPolicy_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.class, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.Builder.class);
        }

        // Construct using dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          minReadaheadMs_ = 0;
          minBandwidthBytesPerSec_ = 0;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.internal_static_video_streaming_PlaybackStartPolicy_ReadaheadPolicy_descriptor;
        }

        @java.lang.Override
        public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy getDefaultInstanceForType() {
          return dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.getDefaultInstance();
        }

        @java.lang.Override
        public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy build() {
          dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy buildPartial() {
          dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy result = new dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy result) {
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.minReadaheadMs_ = minReadaheadMs_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.minBandwidthBytesPerSec_ = minBandwidthBytesPerSec_;
            to_bitField0_ |= 0x00000002;
          }
          result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy) {
            return mergeFrom((dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy other) {
          if (other == dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.getDefaultInstance()) return this;
          if (other.hasMinReadaheadMs()) {
            setMinReadaheadMs(other.getMinReadaheadMs());
          }
          if (other.hasMinBandwidthBytesPerSec()) {
            setMinBandwidthBytesPerSec(other.getMinBandwidthBytesPerSec());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  minBandwidthBytesPerSec_ = input.readInt32();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 8
                case 16: {
                  minReadaheadMs_ = input.readInt32();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 16
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private int minReadaheadMs_ ;
        /**
         * <code>optional int32 min_readahead_ms = 2;</code>
         * @return Whether the minReadaheadMs field is set.
         */
        @java.lang.Override
        public boolean hasMinReadaheadMs() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional int32 min_readahead_ms = 2;</code>
         * @return The minReadaheadMs.
         */
        @java.lang.Override
        public int getMinReadaheadMs() {
          return minReadaheadMs_;
        }
        /**
         * <code>optional int32 min_readahead_ms = 2;</code>
         * @param value The minReadaheadMs to set.
         * @return This builder for chaining.
         */
        public Builder setMinReadaheadMs(int value) {
          
          minReadaheadMs_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 min_readahead_ms = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearMinReadaheadMs() {
          bitField0_ = (bitField0_ & ~0x00000001);
          minReadaheadMs_ = 0;
          onChanged();
          return this;
        }

        private int minBandwidthBytesPerSec_ ;
        /**
         * <code>optional int32 min_bandwidth_bytes_per_sec = 1;</code>
         * @return Whether the minBandwidthBytesPerSec field is set.
         */
        @java.lang.Override
        public boolean hasMinBandwidthBytesPerSec() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional int32 min_bandwidth_bytes_per_sec = 1;</code>
         * @return The minBandwidthBytesPerSec.
         */
        @java.lang.Override
        public int getMinBandwidthBytesPerSec() {
          return minBandwidthBytesPerSec_;
        }
        /**
         * <code>optional int32 min_bandwidth_bytes_per_sec = 1;</code>
         * @param value The minBandwidthBytesPerSec to set.
         * @return This builder for chaining.
         */
        public Builder setMinBandwidthBytesPerSec(int value) {
          
          minBandwidthBytesPerSec_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 min_bandwidth_bytes_per_sec = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearMinBandwidthBytesPerSec() {
          bitField0_ = (bitField0_ & ~0x00000002);
          minBandwidthBytesPerSec_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:video_streaming.PlaybackStartPolicy.ReadaheadPolicy)
      }

      // @@protoc_insertion_point(class_scope:video_streaming.PlaybackStartPolicy.ReadaheadPolicy)
      private static final dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy();
      }

      public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<ReadaheadPolicy>
          PARSER = new com.google.protobuf.AbstractParser<ReadaheadPolicy>() {
        @java.lang.Override
        public ReadaheadPolicy parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<ReadaheadPolicy> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ReadaheadPolicy> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int START_MIN_READAHEAD_POLICY_FIELD_NUMBER = 1;
    private dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy startMinReadaheadPolicy_;
    /**
     * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
     * @return Whether the startMinReadaheadPolicy field is set.
     */
    @java.lang.Override
    public boolean hasStartMinReadaheadPolicy() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
     * @return The startMinReadaheadPolicy.
     */
    @java.lang.Override
    public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy getStartMinReadaheadPolicy() {
      return startMinReadaheadPolicy_ == null ? dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.getDefaultInstance() : startMinReadaheadPolicy_;
    }
    /**
     * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
     */
    @java.lang.Override
    public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicyOrBuilder getStartMinReadaheadPolicyOrBuilder() {
      return startMinReadaheadPolicy_ == null ? dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.getDefaultInstance() : startMinReadaheadPolicy_;
    }

    public static final int RESUME_MIN_READAHEAD_POLICY_FIELD_NUMBER = 2;
    private dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy resumeMinReadaheadPolicy_;
    /**
     * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
     * @return Whether the resumeMinReadaheadPolicy field is set.
     */
    @java.lang.Override
    public boolean hasResumeMinReadaheadPolicy() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
     * @return The resumeMinReadaheadPolicy.
     */
    @java.lang.Override
    public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy getResumeMinReadaheadPolicy() {
      return resumeMinReadaheadPolicy_ == null ? dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.getDefaultInstance() : resumeMinReadaheadPolicy_;
    }
    /**
     * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
     */
    @java.lang.Override
    public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicyOrBuilder getResumeMinReadaheadPolicyOrBuilder() {
      return resumeMinReadaheadPolicy_ == null ? dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.getDefaultInstance() : resumeMinReadaheadPolicy_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getStartMinReadaheadPolicy());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getResumeMinReadaheadPolicy());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStartMinReadaheadPolicy());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResumeMinReadaheadPolicy());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy)) {
        return super.equals(obj);
      }
      dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy other = (dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy) obj;

      if (hasStartMinReadaheadPolicy() != other.hasStartMinReadaheadPolicy()) return false;
      if (hasStartMinReadaheadPolicy()) {
        if (!getStartMinReadaheadPolicy()
            .equals(other.getStartMinReadaheadPolicy())) return false;
      }
      if (hasResumeMinReadaheadPolicy() != other.hasResumeMinReadaheadPolicy()) return false;
      if (hasResumeMinReadaheadPolicy()) {
        if (!getResumeMinReadaheadPolicy()
            .equals(other.getResumeMinReadaheadPolicy())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStartMinReadaheadPolicy()) {
        hash = (37 * hash) + START_MIN_READAHEAD_POLICY_FIELD_NUMBER;
        hash = (53 * hash) + getStartMinReadaheadPolicy().hashCode();
      }
      if (hasResumeMinReadaheadPolicy()) {
        hash = (37 * hash) + RESUME_MIN_READAHEAD_POLICY_FIELD_NUMBER;
        hash = (53 * hash) + getResumeMinReadaheadPolicy().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code video_streaming.PlaybackStartPolicy}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:video_streaming.PlaybackStartPolicy)
        dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.internal_static_video_streaming_PlaybackStartPolicy_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.internal_static_video_streaming_PlaybackStartPolicy_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.class, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.Builder.class);
      }

      // Construct using dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStartMinReadaheadPolicyFieldBuilder();
          getResumeMinReadaheadPolicyFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        startMinReadaheadPolicy_ = null;
        if (startMinReadaheadPolicyBuilder_ != null) {
          startMinReadaheadPolicyBuilder_.dispose();
          startMinReadaheadPolicyBuilder_ = null;
        }
        resumeMinReadaheadPolicy_ = null;
        if (resumeMinReadaheadPolicyBuilder_ != null) {
          resumeMinReadaheadPolicyBuilder_.dispose();
          resumeMinReadaheadPolicyBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.internal_static_video_streaming_PlaybackStartPolicy_descriptor;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy getDefaultInstanceForType() {
        return dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.getDefaultInstance();
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy build() {
        dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy buildPartial() {
        dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy result = new dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.startMinReadaheadPolicy_ = startMinReadaheadPolicyBuilder_ == null
              ? startMinReadaheadPolicy_
              : startMinReadaheadPolicyBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.resumeMinReadaheadPolicy_ = resumeMinReadaheadPolicyBuilder_ == null
              ? resumeMinReadaheadPolicy_
              : resumeMinReadaheadPolicyBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy) {
          return mergeFrom((dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy other) {
        if (other == dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.getDefaultInstance()) return this;
        if (other.hasStartMinReadaheadPolicy()) {
          mergeStartMinReadaheadPolicy(other.getStartMinReadaheadPolicy());
        }
        if (other.hasResumeMinReadaheadPolicy()) {
          mergeResumeMinReadaheadPolicy(other.getResumeMinReadaheadPolicy());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getStartMinReadaheadPolicyFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getResumeMinReadaheadPolicyFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy startMinReadaheadPolicy_;
      private com.google.protobuf.SingleFieldBuilderV3<
          dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.Builder, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicyOrBuilder> startMinReadaheadPolicyBuilder_;
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
       * @return Whether the startMinReadaheadPolicy field is set.
       */
      public boolean hasStartMinReadaheadPolicy() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
       * @return The startMinReadaheadPolicy.
       */
      public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy getStartMinReadaheadPolicy() {
        if (startMinReadaheadPolicyBuilder_ == null) {
          return startMinReadaheadPolicy_ == null ? dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.getDefaultInstance() : startMinReadaheadPolicy_;
        } else {
          return startMinReadaheadPolicyBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
       */
      public Builder setStartMinReadaheadPolicy(dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy value) {
        if (startMinReadaheadPolicyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          startMinReadaheadPolicy_ = value;
        } else {
          startMinReadaheadPolicyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
       */
      public Builder setStartMinReadaheadPolicy(
          dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.Builder builderForValue) {
        if (startMinReadaheadPolicyBuilder_ == null) {
          startMinReadaheadPolicy_ = builderForValue.build();
        } else {
          startMinReadaheadPolicyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
       */
      public Builder mergeStartMinReadaheadPolicy(dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy value) {
        if (startMinReadaheadPolicyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            startMinReadaheadPolicy_ != null &&
            startMinReadaheadPolicy_ != dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.getDefaultInstance()) {
            getStartMinReadaheadPolicyBuilder().mergeFrom(value);
          } else {
            startMinReadaheadPolicy_ = value;
          }
        } else {
          startMinReadaheadPolicyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
       */
      public Builder clearStartMinReadaheadPolicy() {
        bitField0_ = (bitField0_ & ~0x00000001);
        startMinReadaheadPolicy_ = null;
        if (startMinReadaheadPolicyBuilder_ != null) {
          startMinReadaheadPolicyBuilder_.dispose();
          startMinReadaheadPolicyBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
       */
      public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.Builder getStartMinReadaheadPolicyBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getStartMinReadaheadPolicyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
       */
      public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicyOrBuilder getStartMinReadaheadPolicyOrBuilder() {
        if (startMinReadaheadPolicyBuilder_ != null) {
          return startMinReadaheadPolicyBuilder_.getMessageOrBuilder();
        } else {
          return startMinReadaheadPolicy_ == null ?
              dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.getDefaultInstance() : startMinReadaheadPolicy_;
        }
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy start_min_readahead_policy = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.Builder, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicyOrBuilder> 
          getStartMinReadaheadPolicyFieldBuilder() {
        if (startMinReadaheadPolicyBuilder_ == null) {
          startMinReadaheadPolicyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.Builder, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicyOrBuilder>(
                  getStartMinReadaheadPolicy(),
                  getParentForChildren(),
                  isClean());
          startMinReadaheadPolicy_ = null;
        }
        return startMinReadaheadPolicyBuilder_;
      }

      private dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy resumeMinReadaheadPolicy_;
      private com.google.protobuf.SingleFieldBuilderV3<
          dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.Builder, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicyOrBuilder> resumeMinReadaheadPolicyBuilder_;
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
       * @return Whether the resumeMinReadaheadPolicy field is set.
       */
      public boolean hasResumeMinReadaheadPolicy() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
       * @return The resumeMinReadaheadPolicy.
       */
      public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy getResumeMinReadaheadPolicy() {
        if (resumeMinReadaheadPolicyBuilder_ == null) {
          return resumeMinReadaheadPolicy_ == null ? dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.getDefaultInstance() : resumeMinReadaheadPolicy_;
        } else {
          return resumeMinReadaheadPolicyBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
       */
      public Builder setResumeMinReadaheadPolicy(dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy value) {
        if (resumeMinReadaheadPolicyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resumeMinReadaheadPolicy_ = value;
        } else {
          resumeMinReadaheadPolicyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
       */
      public Builder setResumeMinReadaheadPolicy(
          dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.Builder builderForValue) {
        if (resumeMinReadaheadPolicyBuilder_ == null) {
          resumeMinReadaheadPolicy_ = builderForValue.build();
        } else {
          resumeMinReadaheadPolicyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
       */
      public Builder mergeResumeMinReadaheadPolicy(dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy value) {
        if (resumeMinReadaheadPolicyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            resumeMinReadaheadPolicy_ != null &&
            resumeMinReadaheadPolicy_ != dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.getDefaultInstance()) {
            getResumeMinReadaheadPolicyBuilder().mergeFrom(value);
          } else {
            resumeMinReadaheadPolicy_ = value;
          }
        } else {
          resumeMinReadaheadPolicyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
       */
      public Builder clearResumeMinReadaheadPolicy() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resumeMinReadaheadPolicy_ = null;
        if (resumeMinReadaheadPolicyBuilder_ != null) {
          resumeMinReadaheadPolicyBuilder_.dispose();
          resumeMinReadaheadPolicyBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
       */
      public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.Builder getResumeMinReadaheadPolicyBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getResumeMinReadaheadPolicyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
       */
      public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicyOrBuilder getResumeMinReadaheadPolicyOrBuilder() {
        if (resumeMinReadaheadPolicyBuilder_ != null) {
          return resumeMinReadaheadPolicyBuilder_.getMessageOrBuilder();
        } else {
          return resumeMinReadaheadPolicy_ == null ?
              dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.getDefaultInstance() : resumeMinReadaheadPolicy_;
        }
      }
      /**
       * <code>optional .video_streaming.PlaybackStartPolicy.ReadaheadPolicy resume_min_readahead_policy = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.Builder, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicyOrBuilder> 
          getResumeMinReadaheadPolicyFieldBuilder() {
        if (resumeMinReadaheadPolicyBuilder_ == null) {
          resumeMinReadaheadPolicyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicy.Builder, dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy.ReadaheadPolicyOrBuilder>(
                  getResumeMinReadaheadPolicy(),
                  getParentForChildren(),
                  isClean());
          resumeMinReadaheadPolicy_ = null;
        }
        return resumeMinReadaheadPolicyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:video_streaming.PlaybackStartPolicy)
    }

    // @@protoc_insertion_point(class_scope:video_streaming.PlaybackStartPolicy)
    private static final dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy();
    }

    public static dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PlaybackStartPolicy>
        PARSER = new com.google.protobuf.AbstractParser<PlaybackStartPolicy>() {
      @java.lang.Override
      public PlaybackStartPolicy parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlaybackStartPolicy> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlaybackStartPolicy> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.lavalink.youtube.protos.PlaybackStartPolicyOuterClass.PlaybackStartPolicy getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_video_streaming_PlaybackStartPolicy_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_video_streaming_PlaybackStartPolicy_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_video_streaming_PlaybackStartPolicy_ReadaheadPolicy_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_video_streaming_PlaybackStartPolicy_ReadaheadPolicy_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+video_streaming/playback_start_policy." +
      "proto\022\017video_streaming\"\234\002\n\023PlaybackStart" +
      "Policy\022X\n\032start_min_readahead_policy\030\001 \001" +
      "(\01324.video_streaming.PlaybackStartPolicy" +
      ".ReadaheadPolicy\022Y\n\033resume_min_readahead" +
      "_policy\030\002 \001(\01324.video_streaming.Playback" +
      "StartPolicy.ReadaheadPolicy\032P\n\017Readahead" +
      "Policy\022\030\n\020min_readahead_ms\030\002 \001(\005\022#\n\033min_" +
      "bandwidth_bytes_per_sec\030\001 \001(\005B\035\n\033dev.lav" +
      "alink.youtube.protos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_video_streaming_PlaybackStartPolicy_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_video_streaming_PlaybackStartPolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_video_streaming_PlaybackStartPolicy_descriptor,
        new java.lang.String[] { "StartMinReadaheadPolicy", "ResumeMinReadaheadPolicy", });
    internal_static_video_streaming_PlaybackStartPolicy_ReadaheadPolicy_descriptor =
      internal_static_video_streaming_PlaybackStartPolicy_descriptor.getNestedTypes().get(0);
    internal_static_video_streaming_PlaybackStartPolicy_ReadaheadPolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_video_streaming_PlaybackStartPolicy_ReadaheadPolicy_descriptor,
        new java.lang.String[] { "MinReadaheadMs", "MinBandwidthBytesPerSec", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
