// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_streaming/request_cancellation_policy.proto

package dev.lavalink.youtube.protos;

public final class RequestCancellationPolicyOuterClass {
  private RequestCancellationPolicyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestCancellationPolicyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:video_streaming.RequestCancellationPolicy)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 N0 = 1;</code>
     * @return Whether the n0 field is set.
     */
    boolean hasN0();
    /**
     * <code>optional int32 N0 = 1;</code>
     * @return The n0.
     */
    int getN0();

    /**
     * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
     */
    java.util.List<dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item> 
        getItemsList();
    /**
     * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
     */
    dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item getItems(int index);
    /**
     * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
     */
    java.util.List<? extends dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.ItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
     */
    dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.ItemOrBuilder getItemsOrBuilder(
        int index);

    /**
     * <code>optional int32 jq = 3;</code>
     * @return Whether the jq field is set.
     */
    boolean hasJq();
    /**
     * <code>optional int32 jq = 3;</code>
     * @return The jq.
     */
    int getJq();
  }
  /**
   * Protobuf type {@code video_streaming.RequestCancellationPolicy}
   */
  public static final class RequestCancellationPolicy extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:video_streaming.RequestCancellationPolicy)
      RequestCancellationPolicyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestCancellationPolicy.newBuilder() to construct.
    private RequestCancellationPolicy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestCancellationPolicy() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestCancellationPolicy();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.internal_static_video_streaming_RequestCancellationPolicy_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.internal_static_video_streaming_RequestCancellationPolicy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.class, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Builder.class);
    }

    public interface ItemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:video_streaming.RequestCancellationPolicy.Item)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 fR = 1;</code>
       * @return Whether the fR field is set.
       */
      boolean hasFR();
      /**
       * <code>optional int32 fR = 1;</code>
       * @return The fR.
       */
      int getFR();

      /**
       * <code>optional int32 NK = 2;</code>
       * @return Whether the nK field is set.
       */
      boolean hasNK();
      /**
       * <code>optional int32 NK = 2;</code>
       * @return The nK.
       */
      int getNK();

      /**
       * <code>optional int32 minReadaheadMs = 3;</code>
       * @return Whether the minReadaheadMs field is set.
       */
      boolean hasMinReadaheadMs();
      /**
       * <code>optional int32 minReadaheadMs = 3;</code>
       * @return The minReadaheadMs.
       */
      int getMinReadaheadMs();
    }
    /**
     * Protobuf type {@code video_streaming.RequestCancellationPolicy.Item}
     */
    public static final class Item extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:video_streaming.RequestCancellationPolicy.Item)
        ItemOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Item.newBuilder() to construct.
      private Item(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Item() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Item();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.internal_static_video_streaming_RequestCancellationPolicy_Item_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.internal_static_video_streaming_RequestCancellationPolicy_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.class, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.Builder.class);
      }

      private int bitField0_;
      public static final int FR_FIELD_NUMBER = 1;
      private int fR_ = 0;
      /**
       * <code>optional int32 fR = 1;</code>
       * @return Whether the fR field is set.
       */
      @java.lang.Override
      public boolean hasFR() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 fR = 1;</code>
       * @return The fR.
       */
      @java.lang.Override
      public int getFR() {
        return fR_;
      }

      public static final int NK_FIELD_NUMBER = 2;
      private int nK_ = 0;
      /**
       * <code>optional int32 NK = 2;</code>
       * @return Whether the nK field is set.
       */
      @java.lang.Override
      public boolean hasNK() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 NK = 2;</code>
       * @return The nK.
       */
      @java.lang.Override
      public int getNK() {
        return nK_;
      }

      public static final int MINREADAHEADMS_FIELD_NUMBER = 3;
      private int minReadaheadMs_ = 0;
      /**
       * <code>optional int32 minReadaheadMs = 3;</code>
       * @return Whether the minReadaheadMs field is set.
       */
      @java.lang.Override
      public boolean hasMinReadaheadMs() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 minReadaheadMs = 3;</code>
       * @return The minReadaheadMs.
       */
      @java.lang.Override
      public int getMinReadaheadMs() {
        return minReadaheadMs_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeInt32(1, fR_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeInt32(2, nK_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          output.writeInt32(3, minReadaheadMs_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, fR_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, nK_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, minReadaheadMs_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item)) {
          return super.equals(obj);
        }
        dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item other = (dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item) obj;

        if (hasFR() != other.hasFR()) return false;
        if (hasFR()) {
          if (getFR()
              != other.getFR()) return false;
        }
        if (hasNK() != other.hasNK()) return false;
        if (hasNK()) {
          if (getNK()
              != other.getNK()) return false;
        }
        if (hasMinReadaheadMs() != other.hasMinReadaheadMs()) return false;
        if (hasMinReadaheadMs()) {
          if (getMinReadaheadMs()
              != other.getMinReadaheadMs()) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasFR()) {
          hash = (37 * hash) + FR_FIELD_NUMBER;
          hash = (53 * hash) + getFR();
        }
        if (hasNK()) {
          hash = (37 * hash) + NK_FIELD_NUMBER;
          hash = (53 * hash) + getNK();
        }
        if (hasMinReadaheadMs()) {
          hash = (37 * hash) + MINREADAHEADMS_FIELD_NUMBER;
          hash = (53 * hash) + getMinReadaheadMs();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code video_streaming.RequestCancellationPolicy.Item}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:video_streaming.RequestCancellationPolicy.Item)
          dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.ItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.internal_static_video_streaming_RequestCancellationPolicy_Item_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.internal_static_video_streaming_RequestCancellationPolicy_Item_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.class, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.Builder.class);
        }

        // Construct using dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          fR_ = 0;
          nK_ = 0;
          minReadaheadMs_ = 0;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.internal_static_video_streaming_RequestCancellationPolicy_Item_descriptor;
        }

        @java.lang.Override
        public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item getDefaultInstanceForType() {
          return dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.getDefaultInstance();
        }

        @java.lang.Override
        public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item build() {
          dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item buildPartial() {
          dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item result = new dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item result) {
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.fR_ = fR_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.nK_ = nK_;
            to_bitField0_ |= 0x00000002;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.minReadaheadMs_ = minReadaheadMs_;
            to_bitField0_ |= 0x00000004;
          }
          result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item) {
            return mergeFrom((dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item other) {
          if (other == dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.getDefaultInstance()) return this;
          if (other.hasFR()) {
            setFR(other.getFR());
          }
          if (other.hasNK()) {
            setNK(other.getNK());
          }
          if (other.hasMinReadaheadMs()) {
            setMinReadaheadMs(other.getMinReadaheadMs());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  fR_ = input.readInt32();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 8
                case 16: {
                  nK_ = input.readInt32();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 16
                case 24: {
                  minReadaheadMs_ = input.readInt32();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 24
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private int fR_ ;
        /**
         * <code>optional int32 fR = 1;</code>
         * @return Whether the fR field is set.
         */
        @java.lang.Override
        public boolean hasFR() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional int32 fR = 1;</code>
         * @return The fR.
         */
        @java.lang.Override
        public int getFR() {
          return fR_;
        }
        /**
         * <code>optional int32 fR = 1;</code>
         * @param value The fR to set.
         * @return This builder for chaining.
         */
        public Builder setFR(int value) {
          
          fR_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 fR = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearFR() {
          bitField0_ = (bitField0_ & ~0x00000001);
          fR_ = 0;
          onChanged();
          return this;
        }

        private int nK_ ;
        /**
         * <code>optional int32 NK = 2;</code>
         * @return Whether the nK field is set.
         */
        @java.lang.Override
        public boolean hasNK() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional int32 NK = 2;</code>
         * @return The nK.
         */
        @java.lang.Override
        public int getNK() {
          return nK_;
        }
        /**
         * <code>optional int32 NK = 2;</code>
         * @param value The nK to set.
         * @return This builder for chaining.
         */
        public Builder setNK(int value) {
          
          nK_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 NK = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearNK() {
          bitField0_ = (bitField0_ & ~0x00000002);
          nK_ = 0;
          onChanged();
          return this;
        }

        private int minReadaheadMs_ ;
        /**
         * <code>optional int32 minReadaheadMs = 3;</code>
         * @return Whether the minReadaheadMs field is set.
         */
        @java.lang.Override
        public boolean hasMinReadaheadMs() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional int32 minReadaheadMs = 3;</code>
         * @return The minReadaheadMs.
         */
        @java.lang.Override
        public int getMinReadaheadMs() {
          return minReadaheadMs_;
        }
        /**
         * <code>optional int32 minReadaheadMs = 3;</code>
         * @param value The minReadaheadMs to set.
         * @return This builder for chaining.
         */
        public Builder setMinReadaheadMs(int value) {
          
          minReadaheadMs_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 minReadaheadMs = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearMinReadaheadMs() {
          bitField0_ = (bitField0_ & ~0x00000004);
          minReadaheadMs_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:video_streaming.RequestCancellationPolicy.Item)
      }

      // @@protoc_insertion_point(class_scope:video_streaming.RequestCancellationPolicy.Item)
      private static final dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item();
      }

      public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Item>
          PARSER = new com.google.protobuf.AbstractParser<Item>() {
        @java.lang.Override
        public Item parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Item> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Item> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int N0_FIELD_NUMBER = 1;
    private int n0_ = 0;
    /**
     * <code>optional int32 N0 = 1;</code>
     * @return Whether the n0 field is set.
     */
    @java.lang.Override
    public boolean hasN0() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 N0 = 1;</code>
     * @return The n0.
     */
    @java.lang.Override
    public int getN0() {
      return n0_;
    }

    public static final int ITEMS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item> items_;
    /**
     * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
     */
    @java.lang.Override
    public java.util.List<dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.ItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
     */
    @java.lang.Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
     */
    @java.lang.Override
    public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
     */
    @java.lang.Override
    public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.ItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    public static final int JQ_FIELD_NUMBER = 3;
    private int jq_ = 0;
    /**
     * <code>optional int32 jq = 3;</code>
     * @return Whether the jq field is set.
     */
    @java.lang.Override
    public boolean hasJq() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 jq = 3;</code>
     * @return The jq.
     */
    @java.lang.Override
    public int getJq() {
      return jq_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, n0_);
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(2, items_.get(i));
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(3, jq_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, n0_);
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, items_.get(i));
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, jq_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy)) {
        return super.equals(obj);
      }
      dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy other = (dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy) obj;

      if (hasN0() != other.hasN0()) return false;
      if (hasN0()) {
        if (getN0()
            != other.getN0()) return false;
      }
      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (hasJq() != other.hasJq()) return false;
      if (hasJq()) {
        if (getJq()
            != other.getJq()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasN0()) {
        hash = (37 * hash) + N0_FIELD_NUMBER;
        hash = (53 * hash) + getN0();
      }
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      if (hasJq()) {
        hash = (37 * hash) + JQ_FIELD_NUMBER;
        hash = (53 * hash) + getJq();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code video_streaming.RequestCancellationPolicy}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:video_streaming.RequestCancellationPolicy)
        dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.internal_static_video_streaming_RequestCancellationPolicy_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.internal_static_video_streaming_RequestCancellationPolicy_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.class, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Builder.class);
      }

      // Construct using dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        n0_ = 0;
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
        } else {
          items_ = null;
          itemsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        jq_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.internal_static_video_streaming_RequestCancellationPolicy_descriptor;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy getDefaultInstanceForType() {
        return dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.getDefaultInstance();
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy build() {
        dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy buildPartial() {
        dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy result = new dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy result) {
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
      }

      private void buildPartial0(dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.n0_ = n0_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.jq_ = jq_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy) {
          return mergeFrom((dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy other) {
        if (other == dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.getDefaultInstance()) return this;
        if (other.hasN0()) {
          setN0(other.getN0());
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        if (other.hasJq()) {
          setJq(other.getJq());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                n0_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item m =
                    input.readMessage(
                        dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.PARSER,
                        extensionRegistry);
                if (itemsBuilder_ == null) {
                  ensureItemsIsMutable();
                  items_.add(m);
                } else {
                  itemsBuilder_.addMessage(m);
                }
                break;
              } // case 18
              case 24: {
                jq_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int n0_ ;
      /**
       * <code>optional int32 N0 = 1;</code>
       * @return Whether the n0 field is set.
       */
      @java.lang.Override
      public boolean hasN0() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 N0 = 1;</code>
       * @return The n0.
       */
      @java.lang.Override
      public int getN0() {
        return n0_;
      }
      /**
       * <code>optional int32 N0 = 1;</code>
       * @param value The n0 to set.
       * @return This builder for chaining.
       */
      public Builder setN0(int value) {
        
        n0_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 N0 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearN0() {
        bitField0_ = (bitField0_ & ~0x00000001);
        n0_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          items_ = new java.util.ArrayList<dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item>(items_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.Builder, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.ItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public java.util.List<dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public Builder setItems(
          int index, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public Builder setItems(
          int index, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public Builder addItems(dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public Builder addItems(
          int index, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public Builder addItems(
          dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public Builder addItems(
          int index, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.ItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public java.util.List<? extends dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.ItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .video_streaming.RequestCancellationPolicy.Item items = 2;</code>
       */
      public java.util.List<dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.Builder, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.ItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.Item.Builder, dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy.ItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      private int jq_ ;
      /**
       * <code>optional int32 jq = 3;</code>
       * @return Whether the jq field is set.
       */
      @java.lang.Override
      public boolean hasJq() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 jq = 3;</code>
       * @return The jq.
       */
      @java.lang.Override
      public int getJq() {
        return jq_;
      }
      /**
       * <code>optional int32 jq = 3;</code>
       * @param value The jq to set.
       * @return This builder for chaining.
       */
      public Builder setJq(int value) {
        
        jq_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 jq = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearJq() {
        bitField0_ = (bitField0_ & ~0x00000004);
        jq_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:video_streaming.RequestCancellationPolicy)
    }

    // @@protoc_insertion_point(class_scope:video_streaming.RequestCancellationPolicy)
    private static final dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy();
    }

    public static dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RequestCancellationPolicy>
        PARSER = new com.google.protobuf.AbstractParser<RequestCancellationPolicy>() {
      @java.lang.Override
      public RequestCancellationPolicy parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RequestCancellationPolicy> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestCancellationPolicy> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.lavalink.youtube.protos.RequestCancellationPolicyOuterClass.RequestCancellationPolicy getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_video_streaming_RequestCancellationPolicy_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_video_streaming_RequestCancellationPolicy_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_video_streaming_RequestCancellationPolicy_Item_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_video_streaming_RequestCancellationPolicy_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1video_streaming/request_cancellation_p" +
      "olicy.proto\022\017video_streaming\"\253\001\n\031Request" +
      "CancellationPolicy\022\n\n\002N0\030\001 \001(\005\022>\n\005items\030" +
      "\002 \003(\0132/.video_streaming.RequestCancellat" +
      "ionPolicy.Item\022\n\n\002jq\030\003 \001(\005\0326\n\004Item\022\n\n\002fR" +
      "\030\001 \001(\005\022\n\n\002NK\030\002 \001(\005\022\026\n\016minReadaheadMs\030\003 \001" +
      "(\005B\035\n\033dev.lavalink.youtube.protos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_video_streaming_RequestCancellationPolicy_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_video_streaming_RequestCancellationPolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_video_streaming_RequestCancellationPolicy_descriptor,
        new java.lang.String[] { "N0", "Items", "Jq", });
    internal_static_video_streaming_RequestCancellationPolicy_Item_descriptor =
      internal_static_video_streaming_RequestCancellationPolicy_descriptor.getNestedTypes().get(0);
    internal_static_video_streaming_RequestCancellationPolicy_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_video_streaming_RequestCancellationPolicy_Item_descriptor,
        new java.lang.String[] { "FR", "NK", "MinReadaheadMs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
