// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_streaming/sabr_seek.proto

package dev.lavalink.youtube.protos;

public final class SabrSeekOuterClass {
  private SabrSeekOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SabrSeekOrBuilder extends
      // @@protoc_insertion_point(interface_extends:video_streaming.SabrSeek)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 seek_media_time = 1;</code>
     * @return Whether the seekMediaTime field is set.
     */
    boolean hasSeekMediaTime();
    /**
     * <code>optional int64 seek_media_time = 1;</code>
     * @return The seekMediaTime.
     */
    long getSeekMediaTime();

    /**
     * <code>optional int32 seek_media_timescale = 2;</code>
     * @return Whether the seekMediaTimescale field is set.
     */
    boolean hasSeekMediaTimescale();
    /**
     * <code>optional int32 seek_media_timescale = 2;</code>
     * @return The seekMediaTimescale.
     */
    int getSeekMediaTimescale();

    /**
     * <code>optional .misc.SeekSource seek_source = 3;</code>
     * @return Whether the seekSource field is set.
     */
    boolean hasSeekSource();
    /**
     * <code>optional .misc.SeekSource seek_source = 3;</code>
     * @return The seekSource.
     */
    dev.lavalink.youtube.protos.Common.SeekSource getSeekSource();
  }
  /**
   * Protobuf type {@code video_streaming.SabrSeek}
   */
  public static final class SabrSeek extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:video_streaming.SabrSeek)
      SabrSeekOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SabrSeek.newBuilder() to construct.
    private SabrSeek(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SabrSeek() {
      seekSource_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SabrSeek();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.lavalink.youtube.protos.SabrSeekOuterClass.internal_static_video_streaming_SabrSeek_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.lavalink.youtube.protos.SabrSeekOuterClass.internal_static_video_streaming_SabrSeek_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek.class, dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek.Builder.class);
    }

    private int bitField0_;
    public static final int SEEK_MEDIA_TIME_FIELD_NUMBER = 1;
    private long seekMediaTime_ = 0L;
    /**
     * <code>optional int64 seek_media_time = 1;</code>
     * @return Whether the seekMediaTime field is set.
     */
    @java.lang.Override
    public boolean hasSeekMediaTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 seek_media_time = 1;</code>
     * @return The seekMediaTime.
     */
    @java.lang.Override
    public long getSeekMediaTime() {
      return seekMediaTime_;
    }

    public static final int SEEK_MEDIA_TIMESCALE_FIELD_NUMBER = 2;
    private int seekMediaTimescale_ = 0;
    /**
     * <code>optional int32 seek_media_timescale = 2;</code>
     * @return Whether the seekMediaTimescale field is set.
     */
    @java.lang.Override
    public boolean hasSeekMediaTimescale() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 seek_media_timescale = 2;</code>
     * @return The seekMediaTimescale.
     */
    @java.lang.Override
    public int getSeekMediaTimescale() {
      return seekMediaTimescale_;
    }

    public static final int SEEK_SOURCE_FIELD_NUMBER = 3;
    private int seekSource_ = 0;
    /**
     * <code>optional .misc.SeekSource seek_source = 3;</code>
     * @return Whether the seekSource field is set.
     */
    @java.lang.Override public boolean hasSeekSource() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .misc.SeekSource seek_source = 3;</code>
     * @return The seekSource.
     */
    @java.lang.Override public dev.lavalink.youtube.protos.Common.SeekSource getSeekSource() {
      dev.lavalink.youtube.protos.Common.SeekSource result = dev.lavalink.youtube.protos.Common.SeekSource.forNumber(seekSource_);
      return result == null ? dev.lavalink.youtube.protos.Common.SeekSource.SEEK_SOURCE_UNKNOWN : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, seekMediaTime_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, seekMediaTimescale_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, seekSource_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, seekMediaTime_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, seekMediaTimescale_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, seekSource_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek)) {
        return super.equals(obj);
      }
      dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek other = (dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek) obj;

      if (hasSeekMediaTime() != other.hasSeekMediaTime()) return false;
      if (hasSeekMediaTime()) {
        if (getSeekMediaTime()
            != other.getSeekMediaTime()) return false;
      }
      if (hasSeekMediaTimescale() != other.hasSeekMediaTimescale()) return false;
      if (hasSeekMediaTimescale()) {
        if (getSeekMediaTimescale()
            != other.getSeekMediaTimescale()) return false;
      }
      if (hasSeekSource() != other.hasSeekSource()) return false;
      if (hasSeekSource()) {
        if (seekSource_ != other.seekSource_) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSeekMediaTime()) {
        hash = (37 * hash) + SEEK_MEDIA_TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSeekMediaTime());
      }
      if (hasSeekMediaTimescale()) {
        hash = (37 * hash) + SEEK_MEDIA_TIMESCALE_FIELD_NUMBER;
        hash = (53 * hash) + getSeekMediaTimescale();
      }
      if (hasSeekSource()) {
        hash = (37 * hash) + SEEK_SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + seekSource_;
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code video_streaming.SabrSeek}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:video_streaming.SabrSeek)
        dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeekOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.lavalink.youtube.protos.SabrSeekOuterClass.internal_static_video_streaming_SabrSeek_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.lavalink.youtube.protos.SabrSeekOuterClass.internal_static_video_streaming_SabrSeek_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek.class, dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek.Builder.class);
      }

      // Construct using dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        seekMediaTime_ = 0L;
        seekMediaTimescale_ = 0;
        seekSource_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.lavalink.youtube.protos.SabrSeekOuterClass.internal_static_video_streaming_SabrSeek_descriptor;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek getDefaultInstanceForType() {
        return dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek.getDefaultInstance();
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek build() {
        dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek buildPartial() {
        dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek result = new dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.seekMediaTime_ = seekMediaTime_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.seekMediaTimescale_ = seekMediaTimescale_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.seekSource_ = seekSource_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek) {
          return mergeFrom((dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek other) {
        if (other == dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek.getDefaultInstance()) return this;
        if (other.hasSeekMediaTime()) {
          setSeekMediaTime(other.getSeekMediaTime());
        }
        if (other.hasSeekMediaTimescale()) {
          setSeekMediaTimescale(other.getSeekMediaTimescale());
        }
        if (other.hasSeekSource()) {
          setSeekSource(other.getSeekSource());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                seekMediaTime_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                seekMediaTimescale_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                int tmpRaw = input.readEnum();
                dev.lavalink.youtube.protos.Common.SeekSource tmpValue =
                    dev.lavalink.youtube.protos.Common.SeekSource.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(3, tmpRaw);
                } else {
                  seekSource_ = tmpRaw;
                  bitField0_ |= 0x00000004;
                }
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long seekMediaTime_ ;
      /**
       * <code>optional int64 seek_media_time = 1;</code>
       * @return Whether the seekMediaTime field is set.
       */
      @java.lang.Override
      public boolean hasSeekMediaTime() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int64 seek_media_time = 1;</code>
       * @return The seekMediaTime.
       */
      @java.lang.Override
      public long getSeekMediaTime() {
        return seekMediaTime_;
      }
      /**
       * <code>optional int64 seek_media_time = 1;</code>
       * @param value The seekMediaTime to set.
       * @return This builder for chaining.
       */
      public Builder setSeekMediaTime(long value) {
        
        seekMediaTime_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 seek_media_time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeekMediaTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        seekMediaTime_ = 0L;
        onChanged();
        return this;
      }

      private int seekMediaTimescale_ ;
      /**
       * <code>optional int32 seek_media_timescale = 2;</code>
       * @return Whether the seekMediaTimescale field is set.
       */
      @java.lang.Override
      public boolean hasSeekMediaTimescale() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 seek_media_timescale = 2;</code>
       * @return The seekMediaTimescale.
       */
      @java.lang.Override
      public int getSeekMediaTimescale() {
        return seekMediaTimescale_;
      }
      /**
       * <code>optional int32 seek_media_timescale = 2;</code>
       * @param value The seekMediaTimescale to set.
       * @return This builder for chaining.
       */
      public Builder setSeekMediaTimescale(int value) {
        
        seekMediaTimescale_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 seek_media_timescale = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeekMediaTimescale() {
        bitField0_ = (bitField0_ & ~0x00000002);
        seekMediaTimescale_ = 0;
        onChanged();
        return this;
      }

      private int seekSource_ = 0;
      /**
       * <code>optional .misc.SeekSource seek_source = 3;</code>
       * @return Whether the seekSource field is set.
       */
      @java.lang.Override public boolean hasSeekSource() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .misc.SeekSource seek_source = 3;</code>
       * @return The seekSource.
       */
      @java.lang.Override
      public dev.lavalink.youtube.protos.Common.SeekSource getSeekSource() {
        dev.lavalink.youtube.protos.Common.SeekSource result = dev.lavalink.youtube.protos.Common.SeekSource.forNumber(seekSource_);
        return result == null ? dev.lavalink.youtube.protos.Common.SeekSource.SEEK_SOURCE_UNKNOWN : result;
      }
      /**
       * <code>optional .misc.SeekSource seek_source = 3;</code>
       * @param value The seekSource to set.
       * @return This builder for chaining.
       */
      public Builder setSeekSource(dev.lavalink.youtube.protos.Common.SeekSource value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        seekSource_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .misc.SeekSource seek_source = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeekSource() {
        bitField0_ = (bitField0_ & ~0x00000004);
        seekSource_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:video_streaming.SabrSeek)
    }

    // @@protoc_insertion_point(class_scope:video_streaming.SabrSeek)
    private static final dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek();
    }

    public static dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SabrSeek>
        PARSER = new com.google.protobuf.AbstractParser<SabrSeek>() {
      @java.lang.Override
      public SabrSeek parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SabrSeek> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SabrSeek> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.lavalink.youtube.protos.SabrSeekOuterClass.SabrSeek getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_video_streaming_SabrSeek_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_video_streaming_SabrSeek_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037video_streaming/sabr_seek.proto\022\017video" +
      "_streaming\032\021misc/common.proto\"h\n\010SabrSee" +
      "k\022\027\n\017seek_media_time\030\001 \001(\003\022\034\n\024seek_media" +
      "_timescale\030\002 \001(\005\022%\n\013seek_source\030\003 \001(\0162\020." +
      "misc.SeekSourceB\035\n\033dev.lavalink.youtube." +
      "protos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          dev.lavalink.youtube.protos.Common.getDescriptor(),
        });
    internal_static_video_streaming_SabrSeek_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_video_streaming_SabrSeek_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_video_streaming_SabrSeek_descriptor,
        new java.lang.String[] { "SeekMediaTime", "SeekMediaTimescale", "SeekSource", });
    dev.lavalink.youtube.protos.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
