// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_streaming/stream_protection_status.proto

package dev.lavalink.youtube.protos;

public final class StreamProtectionStatusOuterClass {
  private StreamProtectionStatusOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StreamProtectionStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:video_streaming.StreamProtectionStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 status = 1;</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <code>optional int32 status = 1;</code>
     * @return The status.
     */
    int getStatus();

    /**
     * <code>optional int32 field2 = 2;</code>
     * @return Whether the field2 field is set.
     */
    boolean hasField2();
    /**
     * <code>optional int32 field2 = 2;</code>
     * @return The field2.
     */
    int getField2();
  }
  /**
   * Protobuf type {@code video_streaming.StreamProtectionStatus}
   */
  public static final class StreamProtectionStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:video_streaming.StreamProtectionStatus)
      StreamProtectionStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StreamProtectionStatus.newBuilder() to construct.
    private StreamProtectionStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StreamProtectionStatus() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StreamProtectionStatus();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.internal_static_video_streaming_StreamProtectionStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.internal_static_video_streaming_StreamProtectionStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus.class, dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus.Builder.class);
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_ = 0;
    /**
     * <code>optional int32 status = 1;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    public static final int FIELD2_FIELD_NUMBER = 2;
    private int field2_ = 0;
    /**
     * <code>optional int32 field2 = 2;</code>
     * @return Whether the field2 field is set.
     */
    @java.lang.Override
    public boolean hasField2() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 field2 = 2;</code>
     * @return The field2.
     */
    @java.lang.Override
    public int getField2() {
      return field2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, status_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, field2_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, field2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus)) {
        return super.equals(obj);
      }
      dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus other = (dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus) obj;

      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (getStatus()
            != other.getStatus()) return false;
      }
      if (hasField2() != other.hasField2()) return false;
      if (hasField2()) {
        if (getField2()
            != other.getField2()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
      }
      if (hasField2()) {
        hash = (37 * hash) + FIELD2_FIELD_NUMBER;
        hash = (53 * hash) + getField2();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code video_streaming.StreamProtectionStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:video_streaming.StreamProtectionStatus)
        dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.internal_static_video_streaming_StreamProtectionStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.internal_static_video_streaming_StreamProtectionStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus.class, dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus.Builder.class);
      }

      // Construct using dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        status_ = 0;
        field2_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.internal_static_video_streaming_StreamProtectionStatus_descriptor;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus getDefaultInstanceForType() {
        return dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus.getDefaultInstance();
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus build() {
        dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus buildPartial() {
        dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus result = new dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.status_ = status_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.field2_ = field2_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus) {
          return mergeFrom((dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus other) {
        if (other == dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasField2()) {
          setField2(other.getField2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                status_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                field2_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int status_ ;
      /**
       * <code>optional int32 status = 1;</code>
       * @return Whether the status field is set.
       */
      @java.lang.Override
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private int field2_ ;
      /**
       * <code>optional int32 field2 = 2;</code>
       * @return Whether the field2 field is set.
       */
      @java.lang.Override
      public boolean hasField2() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 field2 = 2;</code>
       * @return The field2.
       */
      @java.lang.Override
      public int getField2() {
        return field2_;
      }
      /**
       * <code>optional int32 field2 = 2;</code>
       * @param value The field2 to set.
       * @return This builder for chaining.
       */
      public Builder setField2(int value) {
        
        field2_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 field2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearField2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        field2_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:video_streaming.StreamProtectionStatus)
    }

    // @@protoc_insertion_point(class_scope:video_streaming.StreamProtectionStatus)
    private static final dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus();
    }

    public static dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<StreamProtectionStatus>
        PARSER = new com.google.protobuf.AbstractParser<StreamProtectionStatus>() {
      @java.lang.Override
      public StreamProtectionStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StreamProtectionStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StreamProtectionStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.lavalink.youtube.protos.StreamProtectionStatusOuterClass.StreamProtectionStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_video_streaming_StreamProtectionStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_video_streaming_StreamProtectionStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.video_streaming/stream_protection_stat" +
      "us.proto\022\017video_streaming\"8\n\026StreamProte" +
      "ctionStatus\022\016\n\006status\030\001 \001(\005\022\016\n\006field2\030\002 " +
      "\001(\005B\035\n\033dev.lavalink.youtube.protos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_video_streaming_StreamProtectionStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_video_streaming_StreamProtectionStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_video_streaming_StreamProtectionStatus_descriptor,
        new java.lang.String[] { "Status", "Field2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
